#!/usr/bin/env python3
"""Writes ios/Loupe/Resources/Diagnostics/laya-diagnostics.json from the JVM's pinned Laya fixtures
(backend-onnx/src/test/resources/laya/{golden,criteria}.json): per case the prompt inputs, the token
length and the JVM INT8 / PyTorch probabilities. DEBUG-only in the app (Release excludes the file).

Run from anywhere: python3 ios/scripts/make-diagnostics-fixtures.py
LoupeTests/DiagnosticsTests pins the source fixtures' SHA-256s; update them there when regenerating.
"""
import hashlib
import json
import pathlib

root = pathlib.Path(__file__).resolve().parents[2]
src = root / "backend-onnx/src/test/resources/laya"
out = root / "ios/Loupe/Resources/Diagnostics/laya-diagnostics.json"

cases, sources = [], {}
checkpoint = None
for name in ("golden", "criteria"):
    raw = (src / f"{name}.json").read_bytes()
    sources[name] = hashlib.sha256(raw).hexdigest()
    doc = json.loads(raw)
    checkpoint = checkpoint or doc["checkpoint"]
    for c in doc["cases"]:
        cases.append({
            "set": name,
            "id": c["id"],
            "question": c["question"],
            "state": c["state"],
            "candidates": c["candidates"],
            "descriptions": [d or "" for d in c.get("descriptions", [])],
            "tokens": len(c["inputIds"]),
            "int8": c["expected"]["int8"],
            "torch": c["expected"]["torch"],
        })

doc = {
    "_comment": "GENERATED by ios/scripts/make-diagnostics-fixtures.py from backend-onnx's pinned fixtures. Do not edit.",
    "checkpoint": checkpoint,
    "graphSha256": "8b994315135dd7684331bb58fe3a769e3ca1145a5c421a2a41e2b3c85397b2fa",
    "sources": sources,
    "cases": cases,
}
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(doc, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
print(f"wrote {out.relative_to(root)}: {len(cases)} cases")
