package dev.loupe.kit.site

import dev.loupe.kit.mail.MailMessage
import dev.loupe.kit.mail.Phishing
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * Attacks never score lower than before the branch (fix loop 5): every attack row of the round-5
 * review (scratchpad r5/f1.txt, f2.txt, f3.txt, t1.txt: hrefs with tabs and newlines in the scheme,
 * backslash and slash mixes, HTML character references, userinfo behind CJK punctuation, stand-in
 * dots in a text URL's host) scores at least what origin/main (7e13578) gave it with the same probe
 * (the .b files in loupe-android-evidence/parity-fix5/probes). The floors are origin/main's scores.
 * Generated by loupe-android-evidence/parity-fix5/mklegit.py; HostReadingTest holds the earlier rounds'.
 */
class AttackRowsTest {
    private class Row(val kind: Char, val input: String, val ceiling: Map<String, Int>, val note: Boolean = false)

    private val sender = "\"News\" <news@list.example.org>"

    private fun scores(r: Row): Map<String, Pair<Int, String>> = when (r.kind) {
        'U' -> {
            val site = SiteCheck.checkUrl(r.input).verdict
            val pw = SiteCheck.check(PageFacts(r.input, passwordFields = 1, forms = listOf(PageForm(password = true)))).verdict
            mapOf(
                "SITE" to (site.score to site.level), "PW" to (pw.score to pw.level),
                "MAIL" to Phishing.assess(sender, "", links = listOf(r.input to "Click here")).let { it.score to it.level },
                "SELF" to Phishing.assess(sender, "", links = listOf(r.input to r.input)).let { it.score to it.level },
                "TEXT" to Phishing.assess(sender, "Read more: ${r.input}").let { it.score to it.level },
            )
        }
        'S' -> {
            val f = r.input.split("||")
            mapOf("FROM" to Phishing.assess(f[0], "Your weekly update.", replyTo = f.getOrElse(1) { "" }).let { it.score to it.level })
        }
        'A' -> mapOf("HTML" to Phishing.assess(sender, "", links = MailMessage.anchors(r.input)).let { it.score to it.level })
        else -> mapOf("T" to Phishing.assess(sender, r.input).let { it.score to it.level })
    }

    @Test
    fun `round-5 attacks never score lower than before the branch`() {
        val under = mutableListOf<String>()
        for (r in ROWS) for ((k, got) in scores(r)) {
            val floor = r.ceiling[k] ?: 0
            if (got.first < floor) under += "${r.kind} ${r.input} $k: ${got.first} < $floor"
        }
        assertTrue(under.isEmpty(), under.joinToString("\n"))
    }

    private companion object {
        val ROWS = listOf(
            Row('U', "https://paypa1-secure.xyz/login", mapOf("SITE" to 53, "PW" to 73, "MAIL" to 53, "SELF" to 53, "TEXT" to 53)),
            Row('U', "//paypa1-secure.xyz/login", mapOf("SITE" to 53, "PW" to 73, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "/\\paypa1-secure.xyz/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "\\\\paypa1-secure.xyz/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 8, "SELF" to 8, "TEXT" to 0)),
            Row('U', "\\/paypa1-secure.xyz/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "///paypa1-secure.xyz/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', " //paypa1-secure.xyz/login", mapOf("SITE" to 53, "PW" to 73, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "\u0009//paypa1-secure.xyz/login", mapOf("SITE" to 53, "PW" to 73, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "\u000A/\\paypa1-secure.xyz/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "/\u0009/paypa1-secure.xyz/login", mapOf("SITE" to 53, "PW" to 73, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "/\u0009\\paypa1-secure.xyz/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "\u0001//paypa1-secure.xyz/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "\u00A0https://paypa1-secure.xyz/login", mapOf("SITE" to 53, "PW" to 73, "MAIL" to 53, "SELF" to 53, "TEXT" to 53)),
            Row('U', "\uFEFFhttps://paypa1-secure.xyz/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 53)),
            Row('U', "\u200Bhttps://paypa1-secure.xyz/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 53)),
            Row('U', "%20https://paypa1-secure.xyz/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 53)),
            Row('U', " https://paypa1-secure.xyz/login", mapOf("SITE" to 53, "PW" to 73, "MAIL" to 53, "SELF" to 53, "TEXT" to 53)),
            Row('U', "\u0001https://paypa1-secure.xyz/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 53)),
            Row('U', "h\u0009tps://paypa1-secure.xyz/login", mapOf("SITE" to 53, "PW" to 73, "MAIL" to 53, "SELF" to 53, "TEXT" to 0)),
            Row('U', "ht\u000Atps://paypa1-secure.xyz/login", mapOf("SITE" to 53, "PW" to 73, "MAIL" to 53, "SELF" to 53, "TEXT" to 0)),
            Row('U', "HTTPS://paypa1-secure.xyz/login", mapOf("SITE" to 53, "PW" to 73, "MAIL" to 53, "SELF" to 53, "TEXT" to 53)),
            Row('U', "https:paypa1-secure.xyz/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https:/\\paypa1-secure.xyz/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "//www.paypal.com@paypa1-secure.xyz/login", mapOf("SITE" to 83, "PW" to 100, "MAIL" to 0, "SELF" to 0, "TEXT" to 83)),
            Row('U', "/\\www.paypal.com@paypa1-secure.xyz/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 83)),
            Row('U', "\\\\www.paypal.com@paypa1-secure.xyz/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 83, "SELF" to 100, "TEXT" to 83)),
            Row('U', "//\uFF50\uFF41\uFF59\uFF50\uFF41\uFF4C.com/login", mapOf("SITE" to 45, "PW" to 65, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "/\\\uFF50\uFF41\uFF59\uFF50\uFF41\uFF4C.com/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "//%70aypal.com/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "/\\%70aypal.com/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://%70aypa1.com/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://%70aypal.com/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://www.paypal.com%2Esecure-login.xyz/login", mapOf("SITE" to 38, "PW" to 58, "MAIL" to 38, "SELF" to 68, "TEXT" to 38)),
            Row('U', "https://paypal%2Ecom.evil.tk/login", mapOf("SITE" to 8, "PW" to 8, "MAIL" to 8, "SELF" to 38, "TEXT" to 8)),
            Row('U', "https://pay%70al.com.evil.tk/login", mapOf("SITE" to 8, "PW" to 8, "MAIL" to 8, "SELF" to 8, "TEXT" to 8)),
            Row('U', "https://%70aypal-secure.xyz/login", mapOf("SITE" to 8, "PW" to 8, "MAIL" to 8, "SELF" to 8, "TEXT" to 8)),
            Row('U', "https://ex%61mple.com/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "file:paypa1-secure.xyz/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "file://paypa1-secure.xyz/login", mapOf("SITE" to 53, "PW" to 73, "MAIL" to 53, "SELF" to 53, "TEXT" to 0)),
            Row('U', "file:\\\\paypa1-secure.xyz/share", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "file:/\\paypa1-secure.xyz/share", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "file:////paypa1-secure.xyz/share", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "file:///paypa1-secure.xyz/share", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "file:paypa1-secure.xyz", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://paypal.com\uFF1Bevil.tk/", mapOf("SITE" to 38, "PW" to 58, "MAIL" to 38, "SELF" to 38, "TEXT" to 38)),
            Row('U', "https://www.paypal.com|x@paypa1-secure.xyz/", mapOf("SITE" to 83, "PW" to 100, "MAIL" to 83, "SELF" to 100, "TEXT" to 83)),
            Row('U', "https://\u3002/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://%2e/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://../", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://paypa1-secure.xyz%00/", mapOf("SITE" to 45, "PW" to 65, "MAIL" to 45, "SELF" to 45, "TEXT" to 45)),
            Row('U', "https://.paypa1-secure.xyz/", mapOf("SITE" to 53, "PW" to 73, "MAIL" to 53, "SELF" to 53, "TEXT" to 53)),
            Row('U', "https://paypal.com\u3002/", mapOf("SITE" to 20, "PW" to 40, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u2119aypal.com/", mapOf("SITE" to 45, "PW" to 65, "MAIL" to 45, "SELF" to 45, "TEXT" to 45)),
            Row('U', "https://paypa\u217C.com/", mapOf("SITE" to 45, "PW" to 65, "MAIL" to 45, "SELF" to 45, "TEXT" to 45)),
            Row('U', "https://\uFB01le.com/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u24DFaypal.com/", mapOf("SITE" to 45, "PW" to 65, "MAIL" to 45, "SELF" to 45, "TEXT" to 45)),
            Row('U', "https://pay\u037Epal.com/", mapOf("SITE" to 45, "PW" to 65, "MAIL" to 45, "SELF" to 45, "TEXT" to 45)),
            Row('U', "https://paypal\u037Ecom/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://g\u03BF\u03BFgle.com/", mapOf("SITE" to 60, "PW" to 80, "MAIL" to 60, "SELF" to 60, "TEXT" to 60)),
            Row('U', "https://\u03A9mega.com/", mapOf("SITE" to 35, "PW" to 55, "MAIL" to 35, "SELF" to 35, "TEXT" to 35)),
            Row('U', "https://\u00C5Astra.se/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u212Aeybank.com/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://amazon\u0387com/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u217Ficrosoft.com/", mapOf("SITE" to 45, "PW" to 65, "MAIL" to 45, "SELF" to 45, "TEXT" to 45)),
            Row('U', "https://paypal\uFE52com/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://paypal\u2024com/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u1E9Eparkasse.de/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://pay\u0130pal.com/", mapOf("SITE" to 45, "PW" to 65, "MAIL" to 45, "SELF" to 45, "TEXT" to 45)),
            Row('U', "https://\u0391pple.com/", mapOf("SITE" to 60, "PW" to 80, "MAIL" to 60, "SELF" to 60, "TEXT" to 60)),
            Row('A', "<a href=\"//paypa1-secure.xyz/login\">https://www.paypal.com</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"/paypa1-secure.xyz/login\">https://www.paypal.com</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"\\paypa1-secure.xyz/login\">https://www.paypal.com</a>", mapOf("HTML" to 93)),
            Row('A', "<a href=\"&#92;&#92;paypa1-secure.xyz/login\">Sign in to PayPal</a>", mapOf("HTML" to 30)),
            Row('A', "<a href=\"/&#92;paypa1-secure.xyz/login\">Sign in to PayPal</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\" //paypa1-secure.xyz/login\">Sign in to PayPal</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"&#x09;//paypa1-secure.xyz/login\">Sign in to PayPal</a>", mapOf("HTML" to 30)),
            Row('A', "<a href=\"&#xFEFF;https://paypa1-secure.xyz/login\">Sign in to PayPal</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"&nbsp;https://paypa1-secure.xyz/login\">Sign in to PayPal</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"/paypa1-secure.xyz/login\">Sign in to PayPal</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"//paypa1-secure.xyz/login\">Sign in to PayPal</a>", mapOf("HTML" to 0)),
            Row('U', "ht\u000Atps://paypa1-secure.xyz/login", mapOf("SITE" to 53, "PW" to 73, "MAIL" to 53, "SELF" to 53, "TEXT" to 0)),
            Row('U', "h\u0009ttps://paypa1-secure.xyz/login", mapOf("SITE" to 53, "PW" to 73, "MAIL" to 53, "SELF" to 53, "TEXT" to 0)),
            Row('U', "https\u000A://paypa1-secure.xyz/login", mapOf("SITE" to 53, "PW" to 73, "MAIL" to 53, "SELF" to 53, "TEXT" to 0)),
            Row('U', "https:\u000A//paypa1-secure.xyz/login", mapOf("SITE" to 53, "PW" to 73, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "http\u000Ds://paypa1-secure.xyz/login", mapOf("SITE" to 53, "PW" to 73, "MAIL" to 53, "SELF" to 53, "TEXT" to 0)),
            Row('U', "ht\u000Atps://www.paypal.com@paypa1-secure.xyz/login", mapOf("SITE" to 83, "PW" to 100, "MAIL" to 83, "SELF" to 100, "TEXT" to 83)),
            Row('U', "\u000A\u000Ahttps://paypa1-secure.xyz/login", mapOf("SITE" to 53, "PW" to 73, "MAIL" to 53, "SELF" to 53, "TEXT" to 53)),
            Row('U', "\\\\www.paypal.com@paypa1-secure.xyz/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 83, "SELF" to 100, "TEXT" to 83)),
            Row('U', "\\/www.paypal.com@paypa1-secure.xyz/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 30, "TEXT" to 83)),
            Row('U', "/\\www.paypal.com@paypa1-secure.xyz/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 83)),
            Row('U', "\\\\\uFF50\uFF41\uFF59\uFF50\uFF41\uFF4C.com/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('A', "<a href=\"&#104;ttps://paypa1-secure.xyz/login\">Sign in to PayPal</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"&#104;ttps://www.paypal.com@paypa1-secure.xyz/login\">https://www.paypal.com/</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"&#x68;ttps://paypa1-secure.xyz/login\">https://www.paypal.com/</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"&#47;&#47;paypa1-secure.xyz/login\">https://www.paypal.com/</a>", mapOf("HTML" to 40)),
            Row('A', "<a href=\"&#92;&#92;www.paypal.com@paypa1-secure.xyz/login\">https://www.paypal.com/</a>", mapOf("HTML" to 40)),
            Row('A', "<a href=\"&#92;&#92;paypa1-secure.xyz/login\">https://www.paypal.com/</a>", mapOf("HTML" to 40)),
            Row('A', "<a href=\"https&#58;//paypa1-secure.xyz/login\">Sign in to PayPal</a>", mapOf("HTML" to 30)),
            Row('A', "<a href=\"ht&#10;tps://paypa1-secure.xyz/login\">Sign in to PayPal</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"ht", mapOf("HTML" to 0)),
            Row('t', "s://paypa1-secure.xyz/login\">Sign in to PayPal</a>", mapOf()),
            Row('A', "<a href=\"ht\u0009tps://www.paypal.com@paypa1-secure.xyz/login\">https://www.paypal.com/</a>", mapOf("HTML" to 100)),
            Row('A', "<a href=\"&Tab;https://paypa1-secure.xyz/login\">Sign in to PayPal</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"&NewLine;//paypa1-secure.xyz/login\">https://www.paypal.com/</a>", mapOf("HTML" to 40)),
            Row('A', "<a href=\"&#x20;https://paypa1-secure.xyz/login\">Sign in to PayPal</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"&#1;https://paypa1-secure.xyz/login\">Sign in to PayPal</a>", mapOf("HTML" to 0)),
            Row('U', "https://p%D0%B0ypal.com/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://paypal.com%00.evil.com/", mapOf("SITE" to 30, "PW" to 50, "MAIL" to 30, "SELF" to 30, "TEXT" to 30)),
            Row('U', "https://paypal.com%20evil.com/", mapOf("SITE" to 30, "PW" to 50, "MAIL" to 30, "SELF" to 30, "TEXT" to 30)),
            Row('U', "https://paypal.com%40evil.com/login", mapOf("SITE" to 30, "PW" to 50, "MAIL" to 30, "SELF" to 60, "TEXT" to 30)),
            Row('T', "Log in: https://paypal-secure.xyz/login", mapOf("T" to 43)),
            Row('T', "Log in: https://paypal.com\uFF0Cevil.com/login", mapOf("T" to 30)),
            Row('T', "Log in: www.paypal.com\uFF5Cevil.tk", mapOf("T" to 38)),
            Row('T', "Log in: www.paypal.com|evil.tk", mapOf("T" to 38)),
            Row('T', "Log in: https://paypal\u3002com.evil.xyz/login", mapOf("T" to 8)),
            Row('T', "Log in: www.paypal\u3002com.evil.xyz/login", mapOf("T" to 8)),
            Row('T', "Log in: https://paypal\uFF0Ecom\uFF0Eevil.xyz/login", mapOf("T" to 38)),
            Row('T', "Log in: https://www.paypal.com|login@paypa1-secure.xyz/login", mapOf("T" to 83)),
            Row('T', "Log in: https://www.paypal.com\uFF0Clogin@paypa1-secure.xyz/login", mapOf("T" to 83)),
            Row('T', "Log in: https://www.paypal.com\u060Clogin@paypa1-secure.xyz/login", mapOf("T" to 83)),
            Row('T', "Log in: https://www.paypal.com\u061F@paypa1-secure.xyz/login", mapOf("T" to 83)),
            Row('T', "Log in: https://www.paypal.com\u061B@paypa1-secure.xyz/login", mapOf("T" to 83)),
            Row('T', "Log in: https://www.paypal.com^@paypa1-secure.xyz/login", mapOf("T" to 83)),
            Row('T', "Log in: https://www.paypal.com\u3002login@paypa1-secure.xyz/login", mapOf("T" to 83)),
            Row('T', "Log in: https://www.paypal.com\uFF1A443@paypa1-secure.xyz/login", mapOf("T" to 83)),
            Row('T', "Log in: https://www.paypal.com\u3001@paypa1-secure.xyz/login", mapOf("T" to 83)),
            Row('T', "Log in: https://www.paypal.com\u3010@paypa1-secure.xyz/login", mapOf("T" to 83)),
            Row('T', "Log in: https://www.paypal.com\uFF20paypa1-secure.xyz/login", mapOf("T" to 38)),
            Row('T', "Log in: https://www.paypal.com\uFF5C@paypa1-secure.xyz/login", mapOf("T" to 83)),
            Row('T', "Log in: https://paypal.com:x|y@paypa1-secure.xyz/login", mapOf("T" to 83)),
            Row('T', "Log in: www.paypal.com\u3002evil\u3002xyz/login", mapOf("T" to 0)),
            Row('T', "Log in: www.paypal.com\uFF0Eevil\uFF0Exyz/login", mapOf("T" to 30)),
            Row('T', "Log in: https://www.paypal.com\u3002secure\u3002paypa1-login.xyz/login", mapOf("T" to 38)),
            Row('T', "Log in: https://www.paypal.com\uFF0Esecure\uFF0Epaypa1-login.xyz/login", mapOf("T" to 83)),
            Row('T', "Log in: https://paypal.com\uFF0Eevil.tk/login", mapOf("T" to 38)),
            Row('T', "Log in: https://paypa1.com\uFF0Etk/login", mapOf("T" to 30)),
            Row('T', "Log in: https://paypa1\u3002com/login", mapOf("T" to 0)),
            Row('T', "Log in: https://www.paypal.com\uFF0Eevil\u3002xyz/login", mapOf("T" to 30)),
            Row('T', "Log in: https://www.paypal.com\u3002evil\u3002app/login", mapOf("T" to 0)),
            Row('T', "Log in: https://www.paypal.com%7Cevil.tk/login", mapOf("T" to 38)),
            Row('T', "Log in: https://www.paypal.com%EF%BD%9C@paypa1-secure.xyz/login", mapOf("T" to 83)),
            Row('T', "Log in: https://paypa1-secure.xyz\u3001", mapOf("T" to 45)),
            Row('T', "Log in: https://paypal.com?\uFF5Cpaypa1-secure.xyz", mapOf("T" to 0)),
            Row('T', "Log in: https://paypal.com#\uFF5C@paypa1-secure.xyz", mapOf("T" to 0)),
            Row('T', "Log in: https://paypal.com\uFF0C@paypa1-secure.xyz", mapOf("T" to 83)),
            Row('T', "Log in: https://\uFF50\uFF41\uFF59\uFF50\uFF41\uFF4C.com\uFF0C/login", mapOf("T" to 45)),
            Row('T', "Log in: https://\uFF50\uFF41\uFF59\uFF50\uFF41\uFF4C.com/login", mapOf("T" to 45)),
            Row('T', "Log in: https://%70aypa1.com/login", mapOf("T" to 0)),
            Row('T', "Log in: https://%70aypal.com/login", mapOf("T" to 0)),
            Row('T', "Log in: https://www.paypal.com%2Esecure-login.xyz/login", mapOf("T" to 38)),
            Row('T', "Log in: https://www.paypal.com%2Eevil.tk/login", mapOf("T" to 38)),
        )
    }
}
