package dev.loupe.kit.site

import dev.loupe.kit.mail.MailMessage
import dev.loupe.kit.mail.Phishing
import dev.loupe.sources.common.HtmlText
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Legitimate mail must stay safe (fix loop 4): every legitimate input of the round-4 review
 * (scratchpad r4/p/legit.txt, more.txt, text.txt, text2.txt; round 5: r5/t2.txt; round 6: links side by
 * side in text, r6-work/stitch.txt and st.txt, and newsletters with <base>, r6-work/evidence/nl, capped at 0) scores no higher than on origin/main
 * (7e13578, measured with the same probe: the .b files in loupe-android-evidence/parity-fix4). The ceilings are
 * origin/main's scores. A row marked `note` is a legitimate name with ß, ς or a joiner: it may carry
 * the small deviation note (+10, docs/PHISHING-FORMULA.md §4) and must stay safe. Generated by
 * loupe-android-evidence/parity-fix4/mklegit.py; the companion of HostReadingTest's never-lower tables.
 */
class LegitimateMailTest {
    private class Row(val kind: Char, val input: String, val ceiling: Map<String, Int>, val note: Boolean = false)

    private val sender = "\"News\" <news@list.example.org>"

    private fun scores(r: Row): Map<String, Pair<Int, String>> = when (r.kind) {
        'U' -> {
            val site = SiteCheck.checkUrl(r.input).verdict
            val pw = SiteCheck.check(PageFacts(r.input, passwordFields = 1, forms = listOf(PageForm(password = true)))).verdict
            mapOf(
                "SITE" to (site.score to site.level), "PW" to (pw.score to pw.level),
                "MAIL" to Phishing.assess(sender, "", links = listOf(r.input to "Click here")).let { it.score to it.level },
                "SELF" to Phishing.assess(sender, "", links = listOf(r.input to r.input)).let { it.score to it.level },
                "TEXT" to Phishing.assess(sender, "Read more: ${r.input}").let { it.score to it.level },
            )
        }
        'S' -> {
            val f = r.input.split("||")
            mapOf("FROM" to Phishing.assess(f[0], "Your weekly update.", replyTo = f.getOrElse(1) { "" }).let { it.score to it.level })
        }
        'A' -> mapOf("HTML" to Phishing.assess(sender, "", links = MailMessage.anchors(r.input)).let { it.score to it.level })
        'M' -> r.input.split("\t", limit = 2).let { (snd, t) -> mapOf("T" to Phishing.assess(snd, t).let { it.score to it.level }) }
        'H' -> r.input.split("\t", limit = 2).let { (snd, h) ->
            mapOf("HTML" to Phishing.assess(snd, HtmlText.toText(h), links = MailMessage.anchors(h)).let { it.score to it.level })
        }
        else -> mapOf("T" to Phishing.assess(sender, r.input).let { it.score to it.level })
    }

    @Test
    fun `legitimate mail never scores higher than before the branch`() {
        val over = mutableListOf<String>()
        for (r in ROWS) {
            for ((k, got) in scores(r)) {
                val ceiling = (r.ceiling[k] ?: 0) + if (r.note) 10 else 0
                if (got.first > ceiling || (r.note && got.first > (r.ceiling[k] ?: 0) && got.second != "safe")) {
                    over += "${r.kind} ${r.input} $k: ${got.first} ${got.second} > $ceiling"
                }
            }
        }
        assertTrue(over.isEmpty(), over.joinToString("\n"))
    }

    @Test
    fun `the CJK punctuation rows are safe`() {
        for (t in listOf("访问www.example.com，了解更多", "网址：https://www.example.com；电话", "详情请见（https://www.example.com）。",
            "请访问https://www.example.com！", "请访问https://www.example.com？")) {
            assertEquals("safe", Phishing.assess(sender, t).level, t)
        }
    }

    private companion object {
        val ROWS = listOf(
            Row('U', "https://\u0645\u0648\u0642\u0639.\u0648\u0632\u0627\u0631\u0629-\u0627\u0644\u0627\u062A\u0635\u0627\u0644\u0627\u062A.\u0645\u0635\u0631/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://xn--4gbrim.xn----ymcbaaajlc6dj7bxne2c.xn--wgbh1c/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u0645\u062B\u0627\u0644.\u0625\u062E\u062A\u0628\u0627\u0631/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u0645\u06CC\u200C\u062E\u0648\u0627\u0647\u0645.\u0627\u06CC\u0631\u0627\u0646/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0), note = true),
            Row('U', "https://xn--mgba3gch31f060k.xn--mgba3a4f16a/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0), note = true),
            Row('U', "https://stra\u00DFe.de/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0), note = true),
            Row('U', "https://www.b\u00FCcher.de/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://fa\u00DF.de/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0), note = true),
            Row('U', "https://\u03B5\u03BB\u03BB\u03AC\u03B4\u03B1.gr/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u03B2\u03CC\u03BB\u03BF\u03C2.gr/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0), note = true),
            Row('U', "https://\u03C0\u03B1\u03C1\u03AC\u03B4\u03B5\u03B9\u03B3\u03BC\u03B1.\u03B4\u03BF\u03BA\u03B9\u03BC\u03AE/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u4F8B\u3048.jp/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u65E5\u672C\u8A9E\u3002jp/", mapOf("SITE" to 35, "PW" to 55, "MAIL" to 35, "SELF" to 35, "TEXT" to 35)),
            Row('U', "https://\u4F8B\u3048\u3002\u30C6\u30B9\u30C8/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u4E2D\u56FD\u653F\u5E9C.\u653F\u52A1/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u30C9\u30E1\u30A4\u30F3\u540D\u4F8B.jp/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\uD55C\uAD6D\uC778\uD130\uB137\uC815\uBCF4\uC13C\uD130.\uD55C\uAD6D/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u0E44\u0E17\u0E22.\u0E44\u0E17\u0E22/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u092D\u093E\u0930\u0924.\u092D\u093E\u0930\u0924/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u0921\u093E\u091F\u093E\u092E\u0947\u0932.\u092D\u093E\u0930\u0924/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u095B\u0940.\u092D\u093E\u0930\u0924/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u091C\u093C\u0940.\u092D\u093E\u0930\u0924/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u09AC\u09BE\u0982\u09B2\u09BE.\u09AC\u09BE\u0982\u09B2\u09BE/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u09DC\u09BE.\u09AC\u09BE\u0982\u09B2\u09BE/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u0A2A\u0A70\u0A1C\u0A3E\u0A2C.\u0A2D\u0A3E\u0A30\u0A24/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u0A36\u0A39\u0A3F\u0A30.\u0A2D\u0A3E\u0A30\u0A24/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u05E2\u05D1\u05E8\u05D9\u05EA.\u05D9\u05E9\u05E8\u05D0\u05DC/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u0440\u0444.\u0440\u0444/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u043F\u0440\u0438\u043C\u0435\u0440.\u0438\u0441\u043F\u044B\u0442\u0430\u043D\u0438\u0435/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://caf\u00E9.fr/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u00C9COLE.fr/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://Stra\u00DFe.DE/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0), note = true),
            Row('U', "https://ar.wikipedia.org/wiki/%D9%85%D8%B5%D8%B1", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://www.google.com/search?q=%D9%85%D8%B5%D8%B1&hl=ar", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.com/a%2Fb%3Fc?x=%40%23%25", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.com/%E2%9C%93#frag%20x", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.com/\u0645\u0635\u0631?q=\u0634\u0627\u064A", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://user%40name:p%40ss@example.com/", mapOf("SITE" to 30, "PW" to 50, "MAIL" to 30, "SELF" to 30, "TEXT" to 30)),
            Row('U', "https://example.com:8443/path", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "http://[2001:db8::1]:8080/", mapOf("SITE" to 25, "PW" to 55, "MAIL" to 25, "SELF" to 25, "TEXT" to 0)),
            Row('U', "http://[2001:4860:4860::8888]/", mapOf("SITE" to 25, "PW" to 55, "MAIL" to 25, "SELF" to 25, "TEXT" to 0)),
            Row('U', "http://192.168.1.1/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.com./", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "HTTPS://EXAMPLE.COM/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://en.wikipedia.org/wiki/Special:Search", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://medium.com/@user/post-123", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://www.tiktok.com/@user", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://mastodon.social/@user", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.com/?filter[type]=x&a=b|c", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.com/a[1]^b", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.com/?q=a b", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.com/a\\b", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.com/path?email=a@b.com", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.com/p/@user?next=x@y", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://my_host.example.com/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "http://localhost:3000/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "http://intranet/", mapOf("SITE" to 0, "PW" to 30, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://click.convertkit-mail.com/abc123/xyz?url=https%3A%2F%2Fexample.com%2F", mapOf("SITE" to 45, "PW" to 65, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://u1234.ct.sendgrid.net/ls/click?upn=u001.abcd-2FDef-3D-3D_xyz", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.example.com%2F&data=05%7C01%7Cuser%40example.com%7Cabc%7C&sdata=abc%3D&reserved=0", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://www.google.com/url?q=https://example.com&sa=D", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://urldefense.com/v3/__https://example.com/__;!!ABC\$", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://urldefense.proofpoint.com/v2/url?u=https-3A__example.com&d=DwMFaQ&c=abc&r=x&m=y&s=z&e=", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://protect-eu.mimecast.com/s/abcDEF?domain=example.com", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fexample.com&c=E,1,abc&typo=1", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.us1.list-manage.com/track/click?u=abc&id=def&e=ghi", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://r20.rs6.net/tn.jsp?f=001abc==&c=xyz==&ch=q==", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://mandrillapp.com/track/click/30000/example.com?p=eyJzIjoi", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://email.mg.example.com/c/eJxNj0FuwyAQRc_CrsXYAUJ8B-RjAMGdgGD", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://www.amazon.com/gp/f.html?C=1&R=2&T=C&U=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0&H=abc", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://t.co/abc", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://lnkd.in/xyz", mapOf("SITE" to 10, "PW" to 10, "MAIL" to 5, "SELF" to 5, "TEXT" to 5)),
            Row('A', "<a href=\"mailto:someone@example.com?subject=Hi%20there\">mail</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"MAILTO:x@y.com\">mail</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\" mailto:x@y.com\">mail</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"tel:+20123456\">call</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"sms:+20123456\">sms</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"webcal://example.com/cal.ics\">cal</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"itms-apps://apps.apple.com/app/id123\">app</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"intent://scan/#Intent;scheme=zxing;package=com.x;end\">app</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"whatsapp://send?text=hi\">wa</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"skype:user?call\">skype</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"callto:+20123\">call</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"geo:30.0,31.0\">map</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"maps:?q=cairo\">map</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"zoommtg://zoom.us/join?confno=1\">zoom</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"msteams:/l/meetup-join/19%3ameeting\">teams</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"facetime:+1555\">ft</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"sip:user@example.com\">sip</a>", mapOf("HTML" to 30)),
            Row('A', "<a href=\"spotify:track:abc\">sp</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"market://details?id=com.x\">market</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"fb://profile/123\">fb</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"tg://resolve?domain=x\">tg</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"ftp://ftp.example.com/file.zip\">ftp</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"file:///C:/Users/x.pdf\">file</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"file://server/share/doc.pdf\">file</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"\\\\server\\share\\doc.pdf\">unc</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"wss://example.com/socket\">ws</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"about:blank\">blank</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"/unsubscribe\">unsub</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"/\">home</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"?utm=1\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"./x.html\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"../x.html\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"page.html\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"//example.com/x\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"https://\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"http://\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"https:///\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"*|UNSUB|*\">unsubscribe</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"*|ARCHIVE|*\">view in browser</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"%%unsubscribe%%\">unsubscribe</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"{{unsubscribe_url}}\">unsubscribe</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"[UNSUBSCRIBE]\">unsubscribe</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"<%= url %>\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"\$unsubscribe\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"\u000Ahttps://example.com/ \u000A\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"https://exa\u0009mple.com/\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"https://example.com/?a=1&amp;b=2\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"https://www.paypal.com/signin\">Log in to PayPal</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"https://example.com/\">\uFEE3\uFEAE\uFEA3\uFE92\uFE8E \u0628\u0643\u0645 \uFED3\uFEF2 \uFEE3\uFEEE\uFED7\uFECC\uFEE8\uFE8E</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"https://example.com/\">\uFF57\uFF57\uFF57\uFF0E\uFF45\uFF58\uFF41\uFF4D\uFF50\uFF4C\uFF45\uFF0E\uFF43\uFF4F\uFF4D</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"https://www.rakuten.co.jp/\">\u697D\u5929\u5E02\u5834\u3078</a>", mapOf("HTML" to 0)),
            Row('S', "\"Egypt Post\" <info@egyptpost.org>", mapOf("FROM" to 0)),
            Row('S', "\"B\u00FCcher\" <info@b\u00FCcher.de>", mapOf("FROM" to 0)),
            Row('S', "\"B\u00FCcher\" <info@xn--bcher-kva.de>", mapOf("FROM" to 0)),
            Row('S', "\"\u0645\u064A\u062F\u0627\u0646\" <info@\u0645\u0648\u0642\u0639.\u0648\u0632\u0627\u0631\u0629-\u0627\u0644\u0627\u062A\u0635\u0627\u0644\u0627\u062A.\u0645\u0635\u0631>", mapOf("FROM" to 0)),
            Row('S', "\"Iran\" <info@\u0645\u06CC\u200C\u062E\u0648\u0627\u0647\u0645.\u0627\u06CC\u0631\u0627\u0646>", mapOf("FROM" to 0), note = true),
            Row('S', "\"Japan\" <info@\u4F8B\u3048.jp>", mapOf("FROM" to 0)),
            Row('S', "\"Greek\" <info@\u03B5\u03BB\u03BB\u03AC\u03B4\u03B1.gr>", mapOf("FROM" to 0)),
            Row('S', "\"Strasse\" <info@stra\u00DFe.de>", mapOf("FROM" to 0), note = true),
            Row('S', "\"Hindi\" <info@\u0921\u093E\u091F\u093E\u092E\u0947\u0932.\u092D\u093E\u0930\u0924>", mapOf("FROM" to 0)),
            Row('S', "\"\uFE91\uFEE8\uFEDA \uFEE3\uFEBC\uFEAE\" <news@bm.com.eg>", mapOf("FROM" to 0)),
            Row('S', "\"\uFF21\uFF22\uFF23\u682A\u5F0F\u4F1A\u793E\" <info@abc.co.jp>", mapOf("FROM" to 0)),
            Row('S', "\"\uFF33\uFF2F\uFF26\uFF34\uFF22\uFF21\uFF2E\uFF2B\" <info@softbank.jp>", mapOf("FROM" to 0)),
            Row('S', "\"\uFF32\uFF41\uFF4B\uFF55\uFF54\uFF45\uFF4E\" <info@mail.rakuten.co.jp>", mapOf("FROM" to 0)),
            Row('S', "\"\u5C71\u7530 \u592A\u90CE\" <yamada@example.co.jp>", mapOf("FROM" to 0)),
            Row('S', "\"\u5C71\u7530\uFF20\u4F1A\u793E\" <yamada@example.co.jp>", mapOf("FROM" to 0)),
            Row('S', "\"Shop\" <shop@example.com>||support@example.com", mapOf("FROM" to 0)),
            Row('S', "\"Shop\" <shop@example.com>||\"\u30B5\u30DD\u30FC\u30C8\" <support@\u4F8B\u3048.jp>", mapOf("FROM" to 15)),
            Row('U', "example.com", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "www.b\u00FCcher.de/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "localhost:3000", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "example.com:8080/x", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u09B8\u09AE\u09AF\u09BC.\u09AC\u09BE\u0982\u09B2\u09BE/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u09DF\u09BC.\u09AC\u09BE\u0982\u09B2\u09BE/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u09AF\u09BE\u09BC.\u09AC\u09BE\u0982\u09B2\u09BE/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u03AC\u1F71.gr/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u1F71\u03B8\u03AE\u03BD\u03B1.gr/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('S', "\"Bangla\" <info@\u09DC\u09BE.\u09AC\u09BE\u0982\u09B2\u09BE>", mapOf("FROM" to 0)),
            Row('S', "\"Hindi\" <info@\u095B\u0940.\u092D\u093E\u0930\u0924>", mapOf("FROM" to 0)),
            Row('A', "<a href=\"https://\u09DC\u09BE.\u09AC\u09BE\u0982\u09B2\u09BE/login\">Log in</a>", mapOf("HTML" to 0)),
            Row('T', "Visit https://example.com|Unsubscribe", mapOf("T" to 0)),
            Row('T', "Facebook|Twitter|www.example.com|Privacy", mapOf("T" to 0)),
            Row('T', "Click here<https://www.example.com/>", mapOf("T" to 0)),
            Row('T', "Unsubscribe: https://example.com/u?id=1^2", mapOf("T" to 0)),
            Row('T', "\u8BBF\u95EEwww.example.com\uFF0C\u4E86\u89E3\u66F4\u591A", mapOf("T" to 35)),
            Row('T', "\u8BBF\u95EE www.example.com\uFF0C\u4E86\u89E3\u66F4\u591A", mapOf("T" to 35)),
            Row('T', "\u8BE6\u60C5\u8BF7\u89C1\uFF08https://www.example.com\uFF09\u3002", mapOf("T" to 0)),
            Row('T', "\u8A73\u7D30\u306Fhttps://www.example.co.jp/\u3092\u3054\u89A7\u304F\u3060\u3055\u3044", mapOf("T" to 0)),
            Row('T', "\u8A73\u7D30\u306F www.example.co.jp \u3092\u3054\u89A7\u304F\u3060\u3055\u3044\u3002", mapOf("T" to 0)),
            Row('T', "\u8A73\u7D30\u306F https://www.example.co.jp\u3002", mapOf("T" to 0)),
            Row('T', "\u0632\u0648\u0631\u0648\u0627 www.example.com\u060C \u0634\u0643\u0631\u0627", mapOf("T" to 0)),
            Row('T', "\u0632\u0648\u0631\u0648\u0627 \u0645\u0648\u0642\u0639\u0646\u0627: www.example.com.", mapOf("T" to 0)),
            Row('T', "Mehr unter https://www.example.de/impressum.", mapOf("T" to 0)),
            Row('T', "see https://example.com\\n for details", mapOf("T" to 0)),
            Row('T', "Link: https://example.com/path|x", mapOf("T" to 0)),
            Row('T', "Our site: www.example.com/offers*", mapOf("T" to 0)),
            Row('T', "Reply at https://example.com:8443/x", mapOf("T" to 0)),
            Row('T', "https://ex%61mple.com/tracking", mapOf("T" to 0)),
            Row('T', "\u8BF7\u8BBF\u95EEhttps://www.example.com\u3001\u8C22\u8C22", mapOf("T" to 35)),
            Row('T', "\u8BF7\u8BBF\u95EEhttps://www.example.com\uFF01", mapOf("T" to 0)),
            Row('T', "\u8BF7\u8BBF\u95EEhttps://www.example.com\uFF1F", mapOf("T" to 0)),
            Row('T', "\u7F51\u5740\uFF1Ahttps://www.example.com\uFF1B\u7535\u8BDD", mapOf("T" to 35)),
            Row('T', "\u3010\u5B98\u7F51\u3011https://www.example.com\u3010\u5BA2\u670D\u3011", mapOf("T" to 35)),
            Row('T', "\u300Chttps://www.example.jp\u300D\u3092\u3054\u89A7\u304F\u3060\u3055\u3044", mapOf("T" to 35)),
            Row('T', "\u8A73\u3057\u304F\u306Fhttps://www.example.jp\uFF0F\u3092\u3054\u89A7\u304F\u3060\u3055\u3044", mapOf("T" to 35)),
            Row('T', "\u0647\u0644 \u0632\u0631\u062A www.example.com\u061F", mapOf("T" to 0)),
            Row('T', "Website: www.example.com | Phone: 123", mapOf("T" to 0)),
            Row('T', "Terms:https://example.com/terms|Privacy:https://example.com/privacy", mapOf("T" to 0)),
            Row('T', "https://www.example.com/\u3002", mapOf("T" to 0)),
            Row('T', "\u0632\u0648\u0631\u0648\u0627 \u0645\u0648\u0642\u0639\u0646\u0627 https://www.example.com\u060C \u0634\u0643\u0631\u0627", mapOf("T" to 0)),
            Row('T', "\u0644\u0644\u0645\u0632\u064A\u062F: www.example.com\u061F \u0646\u0639\u0645", mapOf("T" to 0)),
            Row('T', "\u8BE6\u89C1www.example.com\u3002\u8C22\u8C22", mapOf("T" to 35)),
            Row('T', "\u5B98\u7F51\uFF1Ahttps://www.example.cn\uFF5C\u5BA2\u670D\u7535\u8BDD\uFF1A400-000", mapOf("T" to 35)),
            Row('T', "\u5730\u5740https://example.com/a|b|c", mapOf("T" to 0)),
            Row('T', "\u516C\u5F0F\u30B5\u30A4\u30C8\uFF1Ahttps://www.example.co.jp\u3002\u304A\u554F\u3044\u5408\u308F\u305B", mapOf("T" to 35)),
            Row('T', "https://www.example.com/path?x=1|2", mapOf("T" to 0)),
            Row('T', "\u7DB2\u5740\uFF1Ahttps://\u4F8B\u3048.jp\uFF0F", mapOf("T" to 0)),
            Row('T', "Link: https://www.example.com^", mapOf("T" to 0)),
            Row('T', "\u8BBF\u95EE https://www.example.com\uFF0C\u90AE\u7BB1\uFF1Ainfo@example.com", mapOf("T" to 30)),
            Row('T', "Visit www.example.com\uFF5CCall us", mapOf("T" to 0)),
            Row('T', "Website | www.example.com | Tel +20 100 555 0100", mapOf("T" to 0)),
            Row('T', "Website|www.greenleafbakery.com|Tel 0100 555 0100", mapOf("T" to 0)),
            Row('T', "Follow us: facebook.com/greenleafbakery|instagram.com/greenleafbakery", mapOf("T" to 0)),
            Row('T', "Follow us: facebook.com/greenleafbakery|greenleafbakery.com", mapOf("T" to 0)),
            Row('T', "www.facebook.com/nileshoes\uFF5Cwww.nileshoes.com", mapOf("T" to 0)),
            Row('T', "Shop: https://www.amazon.com/shops/nileshoes|https://nileshoes.com", mapOf("T" to 0)),
            Row('T', "Sam|Bistro Cloud|www.bistrocloud.com|+20 100 555 0100", mapOf("T" to 0)),
            Row('T', "www.instagram.com/bistrocloud|www.bistrocloud.com", mapOf("T" to 0)),
            Row('T', "https://github.com/bistrocloud|https://bistrocloud.com", mapOf("T" to 0)),
            Row('T', "Links: linkedin.com/company/acme|acme.io|twitter.com/acme", mapOf("T" to 0)),
            Row('T', "Download: apps.apple.com/app/id123|play.google.com/store/apps/details?id=com.bakery", mapOf("T" to 0)),
            Row('T', "https://www.paypal.com/paypalme/greenleaf|greenleafbakery.com", mapOf("T" to 0)),
            Row('T', "Pay: https://www.paypal.com/paypalme/greenleaf\uFF0Cgreenleafbakery.com", mapOf("T" to 0)),
            Row('T', "www.booking.com/hotel/eg/steigenberger.html|www.steigenberger.com", mapOf("T" to 0)),
            Row('T', "www.amazon.eg/stores/NileShoes\uFF5Cwww.nileshoes.com.eg", mapOf("T" to 0)),
            Row('T', "\u5B98\u7F51\uFF1Awww.example.com.cn\uFF0C\u90AE\u7BB1\uFF1Aservice@example.com.cn\uFF0C\u7535\u8BDD\uFF1A400-800-1234", mapOf("T" to 65)),
            Row('T', "\u5B98\u7F51\uFF1Awww.example.com.cn\uFF5C\u5BA2\u670D\uFF1A400-800-1234\uFF5C\u90AE\u7BB1\uFF1Aservice@example.com.cn", mapOf("T" to 30)),
            Row('T', "\u5FAE\u4FE1\uFF1Aweixin.qq.com\uFF0C\u5B98\u7F51\uFF1Awww.mybakery.cn", mapOf("T" to 0)),
            Row('T', "\u5929\u732B\u65D7\u8230\u5E97\uFF1Ahttps://xyzbrand.tmall.com\uFF5C\u5B98\u7F51\uFF1Ahttps://www.xyzbrand.cn", mapOf("T" to 35)),
            Row('T', "https://xyzbrand.tmall.com\uFF5Chttps://www.xyzbrand.cn", mapOf("T" to 0)),
            Row('T', "\u6DD8\u5B9D\u5E97\u94FA\uFF1Ahttps://shop123.taobao.com\uFF0Chttps://www.mybrand.cn", mapOf("T" to 0)),
            Row('T', "\u4EAC\u4E1C\uFF1Ahttps://mall.jd.com/index-1000.html\uFF0C\u5B98\u7F51\uFF1Awww.mybrand.cn\uFF0C\u7535\u8BDD\uFF1A010-12345678", mapOf("T" to 0)),
            Row('T', "https://www.taobao.com/shop/abc\uFF0Cwww.mybakery.cn", mapOf("T" to 0)),
            Row('T', "Weibo\uFF1Aweibo.com/mybrand\uFF0C\u5B98\u7F51\uFF1Amybrand.cn", mapOf("T" to 0)),
            Row('T', "weibo.com/mybrand\u3001mybrand.cn\u3001douyin.com/mybrand", mapOf("T" to 0)),
            Row('T', "www.google.com\u060Cwww.mybakery.com", mapOf("T" to 30)),
            Row('T', "\u062A\u0627\u0628\u0639\u0648\u0646\u0627: facebook.com/mybakery\u060C mybakery.com", mapOf("T" to 0)),
            Row('T', "\u516C\u5F0F\u30B5\u30A4\u30C8\uFF1Awww.example.co.jp\uFF0F\u304A\u554F\u3044\u5408\u308F\u305B\uFF1Ainfo@example.co.jp", mapOf("T" to 30)),
            Row('T', "\u8A73\u7D30\u306Fhttps://www.amazon.co.jp/dp/B0123\u3001https://www.mybrand.jp", mapOf("T" to 0)),
            Row('T', "https://zoom.us/j/123456789|https://acme.my.salesforce.com/x", mapOf("T" to 0)),
            Row('T', "Docs: https://docs.google.com/document/d/abc/edit|https://acme-wiki.com/page", mapOf("T" to 0)),
            Row('T', "https://www.microsoft.com/en-us/microsoft-365|https://contoso-consulting.com", mapOf("T" to 0)),
            Row('T', "https://www.apple.com/iphone/\uFF0Chttps://www.mystore.eg", mapOf("T" to 0)),
            Row('M', "\"Nile Shoes\" <news@nileshoes.com>\u0009Find us: www.facebook.com/nileshoes\uFF5Cwww.nileshoes.com", mapOf("T" to 0)),
            Row('M', "\"Nile Shoes\" <news@nileshoes.com>\u0009Shop: https://www.amazon.com/shops/nileshoes|https://nileshoes.com", mapOf("T" to 0)),
            Row('M', "\"MyBrand\" <info@mybrand.jp>\u0009\u8A73\u7D30\u306Fhttps://www.amazon.co.jp/dp/B0123\u3001https://www.mybrand.jp", mapOf("T" to 0)),
            Row('M', "\"Green Leaf\" <hello@greenleafbakery.com>\u0009Pay: https://www.paypal.com/paypalme/greenleaf\uFF0Cgreenleafbakery.com", mapOf("T" to 0)),
            Row('H', "\"Nile Shoes\" <news@nileshoes.cn>\u0009<html><body><p>\u672C\u5468\u65B0\u54C1\u4E0A\u67B6\uFF0C\u6B22\u8FCE\u9009\u8D2D\u3002</p>\u000A<p>\u5929\u732B\u65D7\u8230\u5E97\uFF1A<a href=\"https://nileshoes.tmall.com/\">https://nileshoes.tmall.com/</a>\uFF0C\u5B98\u7F51\uFF1A<a href=\"https://www.nileshoes.cn/\">https://www.nileshoes.cn/</a></p>\u000A<p><a href=\"https://www.facebook.com/nileshoes\">www.facebook.com/nileshoes</a>\uFF5C<a href=\"https://www.nileshoes.cn\">www.nileshoes.cn</a></p>\u000A</body></html>\u000A", mapOf("HTML" to 0)),
            Row('H', "\"Amazon.com\" <shipment-tracking@amazon.com>\u0009<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\u000A<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\u000A<head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><title>Your Amazon.com order</title>\u000A<!--[if gte mso 9]><xml><o:OfficeDocumentSettings><o:AllowPNG/><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]-->\u000A<style type=\"text/css\">a[x-apple-data-detectors]{color:inherit !important;} .btn a{color:#fff}</style></head>\u000A<body style=\"margin:0\">\u000A<table role=\"presentation\" width=\"100%\"><tr><td>\u000A<a href=\"https://www.amazon.com/gp/r.html?C=2ADL6J1B0Z1LK&amp;K=3CKHQ1B0VJ7N&amp;M=urn:rtn:msg:20260926&amp;R=1TBLF5&amp;T=C&amp;U=https%3A%2F%2Fwww.amazon.com%2Fgp%2Fcss%2Forder-history%3Fref_%3Dpe_2&amp;H=ABCD&amp;ref_=pe_2\"><img src=\"https://m.media-amazon.com/images/G/01/x-locale/cs/te/logo.png\" alt=\"Amazon.com\" width=\"120\"></a>\u000A<p>Hello Sam,&nbsp;thanks for your order. We&rsquo;ll let you know when it ships &mdash; Order&nbsp;#112-4839201-3829482.</p>\u000A<!--[if mso]>\u000A<v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" href=\"https://www.amazon.com/gp/your-account/order-details?orderID=112-4839201-3829482&amp;ref_=pe_3\" style=\"height:40px;v-text-anchor:middle;width:200px;\" arcsize=\"10%\" fillcolor=\"#FF9900\"><w:anchorlock/><center>View or manage order</center></v:roundrect>\u000A<![endif]-->\u000A<!--[if !mso]><!-- --><a class=\"btn\" href=\"https://www.amazon.com/gp/your-account/order-details?orderID=112-4839201-3829482&amp;ref_=pe_3\" style=\"background:#FF9900;color:#fff\">View or manage order</a><!--<![endif]-->\u000A<p>&copy; 2026 Amazon.com, Inc. or its affiliates. Amazon.com, 410 Terry Avenue N., Seattle, WA 98109-5210.</p>\u000A<p><a href=\"https://www.amazon.com/gp/help/customer/display.html?nodeId=468496&amp;ref_=pe_4\">Help</a> &#124; <a href=\"https://www.amazon.com/privacy\">Privacy&nbsp;Notice</a></p>\u000A<img src=\"https://www.amazon.com/gp/r.html?C=1&amp;T=E&amp;H=x\" width=\"1\" height=\"1\">\u000A</td></tr></table></body></html>\u000A", mapOf("HTML" to 0)),
            Row('H', "\"Apple\" <no_reply@email.apple.com>\u0009<html><head><base href=\"https://www.apple.com/\"></head><body>\u000A<a href=\"/shop/bag?cid=em-us-aos\"><img src=\"/v/email/logo.png\" alt=\"Apple\"></a>\u000A<p>Your AirPods&nbsp;Pro are ready for pickup. Order No.&nbsp;W1234567890.</p>\u000A<a href=\"https://store.apple.com/xc/us/vieworder/W1234567890/sam%40example.com?cid=em-aos\">View your order</a>\u000A<a href=\"/legal/privacy/\">Privacy Policy</a> | <a href=\"https://support.apple.com/contact?cid=em\">Contact us</a>\u000A<p>Copyright &copy; 2026 Apple Inc. One Apple Park Way, Cupertino, CA 95014.</p>\u000A</body></html>\u000A", mapOf("HTML" to 0)),
            Row('H', "\"Green Leaf Bakery\" <hello@greenleafbakery.com>\u0009<!doctype html><html><head><meta charset=\"UTF-8\"><title>*|MC:SUBJECT|*</title>\u000A<base href=\"https://mcusercontent.com/\">\u000A<!--[if mso]><style>table{border-collapse:collapse}</style><![endif]--></head>\u000A<body><center>\u000A<table><tr><td class=\"preheader\" style=\"display:none\">This week at Green Leaf Bakery&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;</td></tr>\u000A<tr><td><a href=\"https://greenleafbakery.us12.list-manage.com/track/click?u=9f8a7b6c5d4e3f2a1b0c9d8e7&amp;id=1a2b3c4d5e&amp;e=0f1e2d3c4b\" target=\"_blank\">View this email in your browser</a></td></tr>\u000A<tr><td><a href=\"https://greenleafbakery.us12.list-manage.com/track/click?u=9f8a7b6c5d4e3f2a1b0c9d8e7&amp;id=6f7a8b9c0d&amp;e=0f1e2d3c4b\"><img alt=\"Green Leaf Bakery\" src=\"images/logo.png\"></a>\u000A<h1>Fresh sourdough &amp; croissants this Saturday!</h1>\u000A<p>Our caf&eacute; opens at 8&nbsp;a.m. &ndash; don&#39;t miss the pain au chocolat. Order at greenleafbakery.com&#8203; or call us.</p>\u000A<a href=\"https://greenleafbakery.us12.list-manage.com/track/click?u=9f8a7b6c5d4e3f2a1b0c9d8e7&amp;id=aa11bb22cc&amp;e=0f1e2d3c4b\" style=\"background:#2e7d32\" class=\"mcnButton\">Order now</a>\u000A<p><a href=\"https://www.facebook.com/greenleafbakery\">Facebook</a> | <a href=\"https://www.instagram.com/greenleafbakery/\">Instagram</a></p>\u000A<p><em>Copyright &copy; 2026 Green Leaf Bakery, All rights reserved.</em><br>\u000A<a href=\"https://greenleafbakery.us12.list-manage.com/profile?u=9f8a7b6c5d4e3f2a1b0c9d8e7&amp;id=1234abcd&amp;e=0f1e2d3c4b&amp;c=5678\">update your preferences</a> or <a href=\"https://greenleafbakery.us12.list-manage.com/unsubscribe?u=9f8a7b6c5d4e3f2a1b0c9d8e7&amp;id=1234abcd&amp;e=0f1e2d3c4b&amp;c=5678\">unsubscribe from this list</a>.</p>\u000A<a href=\"http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&amp;utm_medium=email&amp;utm_campaign=referral_marketing&amp;aid=9f8a&amp;afl=1\"><img src=\"https://eep.io/images/yzco4xsimv0y/5oxI9Jtt6TOq4dLpBW9omb/Q2nfN4YnbQnbFWXfSoPRX6.png\" alt=\"Intuit Mailchimp\"></a>\u000A</td></tr></table></center></body></html>\u000A", mapOf("HTML" to 0)),
            Row('H', "\"LinkedIn\" <messages-noreply@linkedin.com>\u0009<html><body>\u000A<table><tr><td>\u000A<a href=\"https://www.linkedin.com/comm/feed/?lipi=urn%3Ali%3Apage%3Aemail_email_digest_01%3BqK3%2BfGn4T2e&amp;midToken=AQHx&amp;midSig=0x&amp;trk=eml-email_digest_01-header-0-home_glimmer&amp;trkEmail=eml-email_digest_01-header-0-home_glimmer-null-8f3k~m1~6d-null-null&amp;eid=8f3k-m1-6d&amp;otpToken=MTAwNjFlZTE\" style=\"color:#0a66c2\">LinkedIn</a>\u000A<p>Sam, you appeared in 12 searches this week&hellip;</p>\u000A<a href=\"https://www.linkedin.com/comm/me/search-appearances?lipi=urn%3Ali%3Apage%3Aemail&amp;midToken=AQHx&amp;trk=eml-email_digest\">See all searches</a>\u000A<a href=\"https://lnkd.in/eKq9Z8b\">lnkd.in/eKq9Z8b</a>\u000A<p>This email was intended for Sam (Owner at Bistro&nbsp;Cloud). <a href=\"https://www.linkedin.com/help/linkedin/answer/4788?lang=en&amp;lipi=x\">Learn why we included this.</a></p>\u000A<p>&copy; 2026 LinkedIn Corporation, 1&zwnj;000 West Maude Avenue, Sunnyvale, CA 94085. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.</p>\u000A<a href=\"https://www.linkedin.com/comm/psettings/email-unsubscribe?lipi=x&amp;midToken=AQHx&amp;midSig=0x&amp;trk=eml-email_digest&amp;lociId=1\">Unsubscribe</a>\u000A</td></tr></table></body></html>\u000A", mapOf("HTML" to 0)),
            Row('H', "\"Nile Shoes\" <news@nileshoes.com>\u0009<html><head><style>@media only screen and (max-width:480px){.full{width:100%!important}}</style></head><body>\u000A<!-- <a href=\"https://old.example-shop.com/promo\">old promo</a> -->\u000A<div style=\"display:none;max-height:0\">Your weekend deals are here &#847;&zwnj;&nbsp;&#847;&zwnj;&nbsp;&#847;&zwnj;&nbsp;</div>\u000A<a href=\"https://u1234567.ct.sendgrid.net/ls/click?upn=u001.abcDEF-2B7gH9-2FkLmN0pQ-3D-3D&amp;utm_source=newsletter&amp;utm_medium=email\" target=_blank>Shop the sale</a>\u000A<a href='https://u1234567.ct.sendgrid.net/ls/click?upn=u001.XYZ123' target='_blank'>50%&nbsp;off shoes</a>\u000A<a href=https://u1234567.ct.sendgrid.net/ls/click?upn=u001.QRS456 class=cta>View online</a>\u000A<p>Questions? Email <a href=\"mailto:support@nileshoes.com?subject=Order%20help&amp;body=Hi\">support@nileshoes.com</a> or call <a href=\"tel:+20-100-555-0100\">+20&nbsp;100&nbsp;555&nbsp;0100</a>.</p>\u000A<p>Nile Shoes &bull; 12 Tahrir Sq. &bull; Cairo</p>\u000A<a href=\"https://u1234567.ct.sendgrid.net/asm/unsubscribe/?user_id=1234567&amp;data=abc\">Unsubscribe</a> &middot; <a href=\"https://u1234567.ct.sendgrid.net/asm/?user_id=1234567&amp;data=def\">Manage preferences</a>\u000A<img src=\"https://u1234567.ct.sendgrid.net/wf/open?upn=u001.open\" alt=\"\" width=\"1\" height=\"1\" border=\"0\">\u000A</body></html>\u000A", mapOf("HTML" to 0)),
            Row('H', "\"The Weekly Loaf\" <weeklyloaf@substack.com>\u0009<html><body><div class=\"post\">\u000A<h1><a href=\"https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cuZXhhbXBsZS5jb20iLCJwIjoxfQ.abc?j=eyJ1Ijoi\">The Weekly Loaf</a></h1>\u000A<p>&ldquo;Bread is life,&rdquo; she said &mdash; and she wasn&rsquo;t wrong. Read <a href=\"https://open.substack.com/pub/weeklyloaf/p/bread-is-life?r=2abc&amp;utm_campaign=post&amp;utm_medium=email\">the full story</a> or visit https://weeklyloaf.substack.com/archive for more.</p>\u000A<p>Recipe via <a href=\"https://www.nytimes.com/2026/09/20/dining/sourdough.html?smid=em-share\">nytimes.com</a> &amp; <a href=\"https://www.bbc.co.uk/food/recipes/sourdough_bread_15475\">bbc.co.uk</a>.</p>\u000A<p>Links: <a href=\"https://twitter.com/weeklyloaf\">Twitter</a>&nbsp;|&nbsp;<a href=\"https://www.youtube.com/@weeklyloaf\">YouTube</a></p>\u000A<p><a href=\"https://weeklyloaf.substack.com/action/disable_email?token=eyJ1c2VyX2lkIjo\">Unsubscribe</a> &copy; 2026 Weekly Loaf<br>548 Market Street PMB 72296, San Francisco, CA 94104</p>\u000A</div></body></html>\u000A", mapOf("HTML" to 0)),
            Row('H', "\"CIB\" <no-reply@cibeg.com>\u0009<html dir=\"rtl\" lang=\"ar\"><body>\u000A<p>\u0639\u0632\u064A\u0632\u064A \u0627\u0644\u0639\u0645\u064A\u0644\u060C&nbsp;\u062A\u0645 \u062A\u062D\u062F\u064A\u062B \u0634\u0631\u0648\u0637 \u0627\u0644\u062E\u062F\u0645\u0629.</p>\u000A<a href=\"https://www.cibeg.com/ar/personal/terms?utm_source=email&amp;utm_campaign=terms_2026\">\u0627\u0637\u0644\u0639 \u0639\u0644\u0649 \u0627\u0644\u0634\u0631\u0648\u0637</a>\u000A<p>\u0644\u0644\u0627\u0633\u062A\u0641\u0633\u0627\u0631: <a href=\"tel:19666\">19666</a> &#124; <a href=\"https://www.cibeg.com/ar/contact-us\">\u0627\u062A\u0635\u0644 \u0628\u0646\u0627</a></p>\u000A<p>\u0627\u0644\u0628\u0646\u0643 \u0627\u0644\u062A\u062C\u0627\u0631\u064A \u0627\u0644\u062F\u0648\u0644\u064A &copy; 2026</p>\u000A<a href=\"https://www.cibeg.com/ar/unsubscribe?e=a%40b.com&amp;t=1\">\u0625\u0644\u063A\u0627\u0621 \u0627\u0644\u0627\u0634\u062A\u0631\u0627\u0643</a>\u000A</body></html>\u000A", mapOf("HTML" to 0)),
            Row('H', "\"\u793A\u4F8B\" <news@example.com.cn>\u0009<html><body>\u000A<p>\u5C0A\u656C\u7684\u5BA2\u6237\uFF1A\u60A8\u597D\uFF01\u611F\u8C22\u60A8\u8BA2\u9605\u6211\u4EEC\u7684\u65B0\u95FB\u3002</p>\u000A<p>\u5B98\u7F51\uFF1Awww.example.com.cn\uFF5C\u5BA2\u670D\uFF1A400-800-1234\uFF5C\u90AE\u7BB1\uFF1Aservice@example.com.cn</p>\u000A<p>\u7F51\u5740\uFF1Ahttps://www.example.com.cn/news\uFF0C\u4E86\u89E3\u66F4\u591A\u3002\u5FAE\u4FE1\u516C\u4F17\u53F7\uFF1Aexample_cn\u3002</p>\u000A<a href=\"https://www.example.com.cn/news?from=edm&amp;id=20260927\">\u67E5\u770B\u8BE6\u60C5</a>\u000A<a href=\"https://www.example.com.cn/unsubscribe?u=abc&amp;s=1\">\u9000\u8BA2</a>\u000A<p>\u00A9 2026 \u793A\u4F8B\u79D1\u6280\u6709\u9650\u516C\u53F8\u3000\u4EACICP\u590712345678\u53F7</p>\u000A</body></html>\u000A", mapOf("HTML" to 0)),
            Row('H', "\"GitHub\" <notifications@github.com>\u0009<html><body>\u000A<p>@sam-dev requested your review on: <a href=\"https://github.com/bistrocloud/markito/pull/42\">bistrocloud/markito#42</a> Add &lt;scheduler&gt; &amp; retries.</p>\u000A<pre>diff --git a/x.py b/x.py\u000A+ url = \"https://api.example.com/v1?a=1&amp;b=2\"</pre>\u000A<p>&mdash;<br>Reply to this email directly, <a href=\"https://github.com/bistrocloud/markito/pull/42#pullrequestreview-2345\">view it on GitHub</a>, or <a href=\"https://github.com/notifications/unsubscribe-auth/AABBCCDD?e=1\">unsubscribe</a>.<br>You are receiving this because your review was requested.<img src=\"https://github.com/notifications/beacon/AABB.gif\" height=\"1\" width=\"1\" alt=\"\" /><span style=\"color:transparent;display:none\">Message ID: &lt;bistrocloud/markito/pull/42@github.com&gt;</span></p>\u000A<script type=\"application/ld+json\">{\"@context\":\"http://schema.org\",\"@type\":\"EmailMessage\",\"potentialAction\":{\"@type\":\"ViewAction\",\"target\":\"https://github.com/bistrocloud/markito/pull/42\",\"url\":\"https://github.com/bistrocloud/markito/pull/42\",\"name\":\"View Pull Request\"}}</script>\u000A</body></html>\u000A", mapOf("HTML" to 0)),
            Row('H', "\"Acme\" <news@acme.io>\u0009<html><body>\u000A<table><tr><td>\u000A<a href=\"https://d2v8tf04.na1.hubspotlinks.com/Ctc/L2+113/d2V8tF04/VVwN3F5Qgq5bW8Mxx5J5k0dVdW3yF8JK5r8nCdN6hz8Gy3m2mdW7Y8-PT6lZ3n8W1Xz5K46NcD4jW4P4Yx68tLqg9W7bz5Kg4QmvKGW3GSx9Q1W0tlLW4\" data-hs-link-id=\"0\" target=\"_blank\">Register for the webinar</a>\u000A<a href=\"https://www.hubspot.com/?utm_source=email&amp;utm_medium=hs&amp;utm_content=footer\" title=\"HubSpot &gt; Home\">HubSpot</a>\u000A<p>You received this email because you are subscribed to Marketing Information from Acme&nbsp;Corp.<br>\u000A<a href=\"https://hs-1234567.s.hubspotemail.net/hs/manage-preferences/unsubscribe-all?languagePreference=en&amp;d=VnVzG&amp;v=3&amp;_hsenc=p2ANqtz-8&amp;_hsmi=2\">Unsubscribe from all future emails</a></p>\u000A<a href=\"https://acmecorp.com/blog/2026-trends?utm_campaign=Q3&amp;utm_source=hs_email&amp;_hsenc=p2ANqtz--abc&amp;_hsmi=123\">Read: 2026&nbsp;trends &rarr;</a>\u000A</td></tr></table></body></html>\u000A", mapOf("HTML" to 0)),
        )
    }
}
