package dev.loupe.kit.site

import dev.loupe.kit.mail.MailMessage
import dev.loupe.kit.mail.Phishing
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Legitimate mail must stay safe (fix loop 4): every legitimate input of the round-4 review
 * (scratchpad r4/p/legit.txt, more.txt, text.txt, text2.txt; round 5: r5/t2.txt) scores no higher than on origin/main
 * (7e13578, measured with the same probe: the .b files in loupe-android-evidence/parity-fix4). The ceilings are
 * origin/main's scores. A row marked `note` is a legitimate name with ß, ς or a joiner: it may carry
 * the small deviation note (+10, docs/PHISHING-FORMULA.md §4) and must stay safe. Generated by
 * loupe-android-evidence/parity-fix4/mklegit.py; the companion of HostReadingTest's never-lower tables.
 */
class LegitimateMailTest {
    private class Row(val kind: Char, val input: String, val ceiling: Map<String, Int>, val note: Boolean = false)

    private val sender = "\"News\" <news@list.example.org>"

    private fun scores(r: Row): Map<String, Pair<Int, String>> = when (r.kind) {
        'U' -> {
            val site = SiteCheck.checkUrl(r.input).verdict
            val pw = SiteCheck.check(PageFacts(r.input, passwordFields = 1, forms = listOf(PageForm(password = true)))).verdict
            mapOf(
                "SITE" to (site.score to site.level), "PW" to (pw.score to pw.level),
                "MAIL" to Phishing.assess(sender, "", links = listOf(r.input to "Click here")).let { it.score to it.level },
                "SELF" to Phishing.assess(sender, "", links = listOf(r.input to r.input)).let { it.score to it.level },
                "TEXT" to Phishing.assess(sender, "Read more: ${r.input}").let { it.score to it.level },
            )
        }
        'S' -> {
            val f = r.input.split("||")
            mapOf("FROM" to Phishing.assess(f[0], "Your weekly update.", replyTo = f.getOrElse(1) { "" }).let { it.score to it.level })
        }
        'A' -> mapOf("HTML" to Phishing.assess(sender, "", links = MailMessage.anchors(r.input)).let { it.score to it.level })
        else -> mapOf("T" to Phishing.assess(sender, r.input).let { it.score to it.level })
    }

    @Test
    fun `legitimate mail never scores higher than before the branch`() {
        val over = mutableListOf<String>()
        for (r in ROWS) {
            for ((k, got) in scores(r)) {
                val ceiling = (r.ceiling[k] ?: 0) + if (r.note) 10 else 0
                if (got.first > ceiling || (r.note && got.first > (r.ceiling[k] ?: 0) && got.second != "safe")) {
                    over += "${r.kind} ${r.input} $k: ${got.first} ${got.second} > $ceiling"
                }
            }
        }
        assertTrue(over.isEmpty(), over.joinToString("\n"))
    }

    @Test
    fun `the CJK punctuation rows are safe`() {
        for (t in listOf("访问www.example.com，了解更多", "网址：https://www.example.com；电话", "详情请见（https://www.example.com）。",
            "请访问https://www.example.com！", "请访问https://www.example.com？")) {
            assertEquals("safe", Phishing.assess(sender, t).level, t)
        }
    }

    private companion object {
        val ROWS = listOf(
            Row('U', "https://\u0645\u0648\u0642\u0639.\u0648\u0632\u0627\u0631\u0629-\u0627\u0644\u0627\u062A\u0635\u0627\u0644\u0627\u062A.\u0645\u0635\u0631/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://xn--4gbrim.xn----ymcbaaajlc6dj7bxne2c.xn--wgbh1c/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u0645\u062B\u0627\u0644.\u0625\u062E\u062A\u0628\u0627\u0631/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u0645\u06CC\u200C\u062E\u0648\u0627\u0647\u0645.\u0627\u06CC\u0631\u0627\u0646/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0), note = true),
            Row('U', "https://xn--mgba3gch31f060k.xn--mgba3a4f16a/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0), note = true),
            Row('U', "https://stra\u00DFe.de/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0), note = true),
            Row('U', "https://www.b\u00FCcher.de/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://fa\u00DF.de/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0), note = true),
            Row('U', "https://\u03B5\u03BB\u03BB\u03AC\u03B4\u03B1.gr/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u03B2\u03CC\u03BB\u03BF\u03C2.gr/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0), note = true),
            Row('U', "https://\u03C0\u03B1\u03C1\u03AC\u03B4\u03B5\u03B9\u03B3\u03BC\u03B1.\u03B4\u03BF\u03BA\u03B9\u03BC\u03AE/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u4F8B\u3048.jp/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u65E5\u672C\u8A9E\u3002jp/", mapOf("SITE" to 35, "PW" to 55, "MAIL" to 35, "SELF" to 35, "TEXT" to 35)),
            Row('U', "https://\u4F8B\u3048\u3002\u30C6\u30B9\u30C8/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u4E2D\u56FD\u653F\u5E9C.\u653F\u52A1/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u30C9\u30E1\u30A4\u30F3\u540D\u4F8B.jp/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\uD55C\uAD6D\uC778\uD130\uB137\uC815\uBCF4\uC13C\uD130.\uD55C\uAD6D/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u0E44\u0E17\u0E22.\u0E44\u0E17\u0E22/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u092D\u093E\u0930\u0924.\u092D\u093E\u0930\u0924/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u0921\u093E\u091F\u093E\u092E\u0947\u0932.\u092D\u093E\u0930\u0924/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u095B\u0940.\u092D\u093E\u0930\u0924/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u091C\u093C\u0940.\u092D\u093E\u0930\u0924/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u09AC\u09BE\u0982\u09B2\u09BE.\u09AC\u09BE\u0982\u09B2\u09BE/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u09DC\u09BE.\u09AC\u09BE\u0982\u09B2\u09BE/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u0A2A\u0A70\u0A1C\u0A3E\u0A2C.\u0A2D\u0A3E\u0A30\u0A24/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u0A36\u0A39\u0A3F\u0A30.\u0A2D\u0A3E\u0A30\u0A24/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u05E2\u05D1\u05E8\u05D9\u05EA.\u05D9\u05E9\u05E8\u05D0\u05DC/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u0440\u0444.\u0440\u0444/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u043F\u0440\u0438\u043C\u0435\u0440.\u0438\u0441\u043F\u044B\u0442\u0430\u043D\u0438\u0435/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://caf\u00E9.fr/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u00C9COLE.fr/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://Stra\u00DFe.DE/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0), note = true),
            Row('U', "https://ar.wikipedia.org/wiki/%D9%85%D8%B5%D8%B1", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://www.google.com/search?q=%D9%85%D8%B5%D8%B1&hl=ar", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.com/a%2Fb%3Fc?x=%40%23%25", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.com/%E2%9C%93#frag%20x", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.com/\u0645\u0635\u0631?q=\u0634\u0627\u064A", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://user%40name:p%40ss@example.com/", mapOf("SITE" to 30, "PW" to 50, "MAIL" to 30, "SELF" to 30, "TEXT" to 30)),
            Row('U', "https://example.com:8443/path", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "http://[2001:db8::1]:8080/", mapOf("SITE" to 25, "PW" to 55, "MAIL" to 25, "SELF" to 25, "TEXT" to 0)),
            Row('U', "http://[2001:4860:4860::8888]/", mapOf("SITE" to 25, "PW" to 55, "MAIL" to 25, "SELF" to 25, "TEXT" to 0)),
            Row('U', "http://192.168.1.1/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.com./", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "HTTPS://EXAMPLE.COM/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://en.wikipedia.org/wiki/Special:Search", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://medium.com/@user/post-123", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://www.tiktok.com/@user", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://mastodon.social/@user", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.com/?filter[type]=x&a=b|c", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.com/a[1]^b", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.com/?q=a b", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.com/a\\b", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.com/path?email=a@b.com", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.com/p/@user?next=x@y", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://my_host.example.com/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "http://localhost:3000/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "http://intranet/", mapOf("SITE" to 0, "PW" to 30, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://click.convertkit-mail.com/abc123/xyz?url=https%3A%2F%2Fexample.com%2F", mapOf("SITE" to 45, "PW" to 65, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://u1234.ct.sendgrid.net/ls/click?upn=u001.abcd-2FDef-3D-3D_xyz", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.example.com%2F&data=05%7C01%7Cuser%40example.com%7Cabc%7C&sdata=abc%3D&reserved=0", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://www.google.com/url?q=https://example.com&sa=D", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://urldefense.com/v3/__https://example.com/__;!!ABC\$", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://urldefense.proofpoint.com/v2/url?u=https-3A__example.com&d=DwMFaQ&c=abc&r=x&m=y&s=z&e=", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://protect-eu.mimecast.com/s/abcDEF?domain=example.com", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fexample.com&c=E,1,abc&typo=1", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://example.us1.list-manage.com/track/click?u=abc&id=def&e=ghi", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://r20.rs6.net/tn.jsp?f=001abc==&c=xyz==&ch=q==", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://mandrillapp.com/track/click/30000/example.com?p=eyJzIjoi", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://email.mg.example.com/c/eJxNj0FuwyAQRc_CrsXYAUJ8B-RjAMGdgGD", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://www.amazon.com/gp/f.html?C=1&R=2&T=C&U=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB0&H=abc", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://t.co/abc", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://lnkd.in/xyz", mapOf("SITE" to 10, "PW" to 10, "MAIL" to 5, "SELF" to 5, "TEXT" to 5)),
            Row('A', "<a href=\"mailto:someone@example.com?subject=Hi%20there\">mail</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"MAILTO:x@y.com\">mail</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\" mailto:x@y.com\">mail</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"tel:+20123456\">call</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"sms:+20123456\">sms</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"webcal://example.com/cal.ics\">cal</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"itms-apps://apps.apple.com/app/id123\">app</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"intent://scan/#Intent;scheme=zxing;package=com.x;end\">app</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"whatsapp://send?text=hi\">wa</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"skype:user?call\">skype</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"callto:+20123\">call</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"geo:30.0,31.0\">map</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"maps:?q=cairo\">map</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"zoommtg://zoom.us/join?confno=1\">zoom</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"msteams:/l/meetup-join/19%3ameeting\">teams</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"facetime:+1555\">ft</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"sip:user@example.com\">sip</a>", mapOf("HTML" to 30)),
            Row('A', "<a href=\"spotify:track:abc\">sp</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"market://details?id=com.x\">market</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"fb://profile/123\">fb</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"tg://resolve?domain=x\">tg</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"ftp://ftp.example.com/file.zip\">ftp</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"file:///C:/Users/x.pdf\">file</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"file://server/share/doc.pdf\">file</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"\\\\server\\share\\doc.pdf\">unc</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"wss://example.com/socket\">ws</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"about:blank\">blank</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"/unsubscribe\">unsub</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"/\">home</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"?utm=1\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"./x.html\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"../x.html\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"page.html\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"//example.com/x\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"https://\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"http://\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"https:///\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"*|UNSUB|*\">unsubscribe</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"*|ARCHIVE|*\">view in browser</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"%%unsubscribe%%\">unsubscribe</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"{{unsubscribe_url}}\">unsubscribe</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"[UNSUBSCRIBE]\">unsubscribe</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"<%= url %>\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"\$unsubscribe\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"\u000Ahttps://example.com/ \u000A\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"https://exa\u0009mple.com/\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"https://example.com/?a=1&amp;b=2\">x</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"https://www.paypal.com/signin\">Log in to PayPal</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"https://example.com/\">\uFEE3\uFEAE\uFEA3\uFE92\uFE8E \u0628\u0643\u0645 \uFED3\uFEF2 \uFEE3\uFEEE\uFED7\uFECC\uFEE8\uFE8E</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"https://example.com/\">\uFF57\uFF57\uFF57\uFF0E\uFF45\uFF58\uFF41\uFF4D\uFF50\uFF4C\uFF45\uFF0E\uFF43\uFF4F\uFF4D</a>", mapOf("HTML" to 0)),
            Row('A', "<a href=\"https://www.rakuten.co.jp/\">\u697D\u5929\u5E02\u5834\u3078</a>", mapOf("HTML" to 0)),
            Row('S', "\"Egypt Post\" <info@egyptpost.org>", mapOf("FROM" to 0)),
            Row('S', "\"B\u00FCcher\" <info@b\u00FCcher.de>", mapOf("FROM" to 0)),
            Row('S', "\"B\u00FCcher\" <info@xn--bcher-kva.de>", mapOf("FROM" to 0)),
            Row('S', "\"\u0645\u064A\u062F\u0627\u0646\" <info@\u0645\u0648\u0642\u0639.\u0648\u0632\u0627\u0631\u0629-\u0627\u0644\u0627\u062A\u0635\u0627\u0644\u0627\u062A.\u0645\u0635\u0631>", mapOf("FROM" to 0)),
            Row('S', "\"Iran\" <info@\u0645\u06CC\u200C\u062E\u0648\u0627\u0647\u0645.\u0627\u06CC\u0631\u0627\u0646>", mapOf("FROM" to 0), note = true),
            Row('S', "\"Japan\" <info@\u4F8B\u3048.jp>", mapOf("FROM" to 0)),
            Row('S', "\"Greek\" <info@\u03B5\u03BB\u03BB\u03AC\u03B4\u03B1.gr>", mapOf("FROM" to 0)),
            Row('S', "\"Strasse\" <info@stra\u00DFe.de>", mapOf("FROM" to 0), note = true),
            Row('S', "\"Hindi\" <info@\u0921\u093E\u091F\u093E\u092E\u0947\u0932.\u092D\u093E\u0930\u0924>", mapOf("FROM" to 0)),
            Row('S', "\"\uFE91\uFEE8\uFEDA \uFEE3\uFEBC\uFEAE\" <news@bm.com.eg>", mapOf("FROM" to 0)),
            Row('S', "\"\uFF21\uFF22\uFF23\u682A\u5F0F\u4F1A\u793E\" <info@abc.co.jp>", mapOf("FROM" to 0)),
            Row('S', "\"\uFF33\uFF2F\uFF26\uFF34\uFF22\uFF21\uFF2E\uFF2B\" <info@softbank.jp>", mapOf("FROM" to 0)),
            Row('S', "\"\uFF32\uFF41\uFF4B\uFF55\uFF54\uFF45\uFF4E\" <info@mail.rakuten.co.jp>", mapOf("FROM" to 0)),
            Row('S', "\"\u5C71\u7530 \u592A\u90CE\" <yamada@example.co.jp>", mapOf("FROM" to 0)),
            Row('S', "\"\u5C71\u7530\uFF20\u4F1A\u793E\" <yamada@example.co.jp>", mapOf("FROM" to 0)),
            Row('S', "\"Shop\" <shop@example.com>||support@example.com", mapOf("FROM" to 0)),
            Row('S', "\"Shop\" <shop@example.com>||\"\u30B5\u30DD\u30FC\u30C8\" <support@\u4F8B\u3048.jp>", mapOf("FROM" to 15)),
            Row('U', "example.com", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "www.b\u00FCcher.de/login", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "localhost:3000", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "example.com:8080/x", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u09B8\u09AE\u09AF\u09BC.\u09AC\u09BE\u0982\u09B2\u09BE/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u09DF\u09BC.\u09AC\u09BE\u0982\u09B2\u09BE/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u09AF\u09BE\u09BC.\u09AC\u09BE\u0982\u09B2\u09BE/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u03AC\u1F71.gr/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('U', "https://\u1F71\u03B8\u03AE\u03BD\u03B1.gr/", mapOf("SITE" to 0, "PW" to 0, "MAIL" to 0, "SELF" to 0, "TEXT" to 0)),
            Row('S', "\"Bangla\" <info@\u09DC\u09BE.\u09AC\u09BE\u0982\u09B2\u09BE>", mapOf("FROM" to 0)),
            Row('S', "\"Hindi\" <info@\u095B\u0940.\u092D\u093E\u0930\u0924>", mapOf("FROM" to 0)),
            Row('A', "<a href=\"https://\u09DC\u09BE.\u09AC\u09BE\u0982\u09B2\u09BE/login\">Log in</a>", mapOf("HTML" to 0)),
            Row('T', "Visit https://example.com|Unsubscribe", mapOf("T" to 0)),
            Row('T', "Facebook|Twitter|www.example.com|Privacy", mapOf("T" to 0)),
            Row('T', "Click here<https://www.example.com/>", mapOf("T" to 0)),
            Row('T', "Unsubscribe: https://example.com/u?id=1^2", mapOf("T" to 0)),
            Row('T', "\u8BBF\u95EEwww.example.com\uFF0C\u4E86\u89E3\u66F4\u591A", mapOf("T" to 35)),
            Row('T', "\u8BBF\u95EE www.example.com\uFF0C\u4E86\u89E3\u66F4\u591A", mapOf("T" to 35)),
            Row('T', "\u8BE6\u60C5\u8BF7\u89C1\uFF08https://www.example.com\uFF09\u3002", mapOf("T" to 0)),
            Row('T', "\u8A73\u7D30\u306Fhttps://www.example.co.jp/\u3092\u3054\u89A7\u304F\u3060\u3055\u3044", mapOf("T" to 0)),
            Row('T', "\u8A73\u7D30\u306F www.example.co.jp \u3092\u3054\u89A7\u304F\u3060\u3055\u3044\u3002", mapOf("T" to 0)),
            Row('T', "\u8A73\u7D30\u306F https://www.example.co.jp\u3002", mapOf("T" to 0)),
            Row('T', "\u0632\u0648\u0631\u0648\u0627 www.example.com\u060C \u0634\u0643\u0631\u0627", mapOf("T" to 0)),
            Row('T', "\u0632\u0648\u0631\u0648\u0627 \u0645\u0648\u0642\u0639\u0646\u0627: www.example.com.", mapOf("T" to 0)),
            Row('T', "Mehr unter https://www.example.de/impressum.", mapOf("T" to 0)),
            Row('T', "see https://example.com\\n for details", mapOf("T" to 0)),
            Row('T', "Link: https://example.com/path|x", mapOf("T" to 0)),
            Row('T', "Our site: www.example.com/offers*", mapOf("T" to 0)),
            Row('T', "Reply at https://example.com:8443/x", mapOf("T" to 0)),
            Row('T', "https://ex%61mple.com/tracking", mapOf("T" to 0)),
            Row('T', "\u8BF7\u8BBF\u95EEhttps://www.example.com\u3001\u8C22\u8C22", mapOf("T" to 35)),
            Row('T', "\u8BF7\u8BBF\u95EEhttps://www.example.com\uFF01", mapOf("T" to 0)),
            Row('T', "\u8BF7\u8BBF\u95EEhttps://www.example.com\uFF1F", mapOf("T" to 0)),
            Row('T', "\u7F51\u5740\uFF1Ahttps://www.example.com\uFF1B\u7535\u8BDD", mapOf("T" to 35)),
            Row('T', "\u3010\u5B98\u7F51\u3011https://www.example.com\u3010\u5BA2\u670D\u3011", mapOf("T" to 35)),
            Row('T', "\u300Chttps://www.example.jp\u300D\u3092\u3054\u89A7\u304F\u3060\u3055\u3044", mapOf("T" to 35)),
            Row('T', "\u8A73\u3057\u304F\u306Fhttps://www.example.jp\uFF0F\u3092\u3054\u89A7\u304F\u3060\u3055\u3044", mapOf("T" to 35)),
            Row('T', "\u0647\u0644 \u0632\u0631\u062A www.example.com\u061F", mapOf("T" to 0)),
            Row('T', "Website: www.example.com | Phone: 123", mapOf("T" to 0)),
            Row('T', "Terms:https://example.com/terms|Privacy:https://example.com/privacy", mapOf("T" to 0)),
            Row('T', "https://www.example.com/\u3002", mapOf("T" to 0)),
            Row('T', "\u0632\u0648\u0631\u0648\u0627 \u0645\u0648\u0642\u0639\u0646\u0627 https://www.example.com\u060C \u0634\u0643\u0631\u0627", mapOf("T" to 0)),
            Row('T', "\u0644\u0644\u0645\u0632\u064A\u062F: www.example.com\u061F \u0646\u0639\u0645", mapOf("T" to 0)),
            Row('T', "\u8BE6\u89C1www.example.com\u3002\u8C22\u8C22", mapOf("T" to 35)),
            Row('T', "\u5B98\u7F51\uFF1Ahttps://www.example.cn\uFF5C\u5BA2\u670D\u7535\u8BDD\uFF1A400-000", mapOf("T" to 35)),
            Row('T', "\u5730\u5740https://example.com/a|b|c", mapOf("T" to 0)),
            Row('T', "\u516C\u5F0F\u30B5\u30A4\u30C8\uFF1Ahttps://www.example.co.jp\u3002\u304A\u554F\u3044\u5408\u308F\u305B", mapOf("T" to 35)),
            Row('T', "https://www.example.com/path?x=1|2", mapOf("T" to 0)),
            Row('T', "\u7DB2\u5740\uFF1Ahttps://\u4F8B\u3048.jp\uFF0F", mapOf("T" to 0)),
            Row('T', "Link: https://www.example.com^", mapOf("T" to 0)),
            Row('T', "\u8BBF\u95EE https://www.example.com\uFF0C\u90AE\u7BB1\uFF1Ainfo@example.com", mapOf("T" to 30)),
            Row('T', "Visit www.example.com\uFF5CCall us", mapOf("T" to 0)),
        )
    }
}
