#!/usr/bin/env python3
"""Generates loupe-kit's HtmlEntitiesData.kt from the WHATWG HTML named character references
(Python's html.entities.html5, which is that table). Usage: gen_entities.py [--check]"""
import html.entities, sys, pathlib
OUT = pathlib.Path(__file__).resolve().parents[2] / "loupe-kit/src/commonMain/kotlin/dev/loupe/kit/mail/HtmlEntitiesData.kt"
t = html.entities.html5
full = sorted(k[:-1] for k in t if k.endswith(";"))
legacy = sorted(k for k in t if not k.endswith(";"))
entries = [n + "=" + ",".join("%X" % ord(c) for c in t[n + ";"]) for n in full]
chunks, cur = [], []
for e in entries:  # whole entries per chunk, each chunk under the class-file constant limit
    if cur and len(" ".join(cur + [e])) > 16000:
        chunks.append(" ".join(cur)); cur = []
    cur.append(e)
chunks.append(" ".join(cur))
src = ["// GENERATED by tools/html/gen_entities.py from the WHATWG named character references", "// (%d names, %d also without a semicolon). Do not edit." % (len(full), len(legacy)),
       "package dev.loupe.kit.mail", "", "internal object HtmlEntitiesData {",
       "    /** `name=HEX[,HEX]` separated by spaces, split to stay under the class-file constant limit. */",
       "    val TABLE: List<String> = listOf("]
src += ['        "%s",' % c for c in chunks]
src += ["    )", "", "    /** The names HTML also decodes without the semicolon (legacy). */",
        "    const val LEGACY: String = \"%s\"" % " ".join(legacy), "}", ""]
text = "\n".join(src)
if "--check" in sys.argv:
    sys.exit(0 if OUT.read_text() == text else "HtmlEntitiesData.kt is stale")
OUT.write_text(text)
print(len(full), len(legacy), len(text))
