import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    kotlin("multiplatform")
}

// Loupe for Android (docs/ANDROID-PLAN.md): an Android library target beside JVM and iOS, only where
// settings.gradle.kts found an Android SDK (it says so when it did not).
val androidHost = gradle.extra["loupe.android"] as Boolean
if (androidHost) apply(plugin = "com.android.library")

repositories {
    mavenCentral()
    google()
}

// ---- Generated sources -------------------------------------------------------------------------
//
// Kotlin/Native has no classpath resources, so the PSL snapshot reaches iOS as a Kotlin string
// constant generated from the very same bytes the JVM reads from its resources. The output is a
// pure function of the input file, so it is deterministic and cacheable.

val pslDir = layout.projectDirectory.dir("src/jvmMain/resources/dev/loupe/engine")

fun kotlinStringChunks(text: String, chunk: Int = 8_000): String {
    val out = StringBuilder()
    var i = 0
    while (i < text.length) {
        var end = minOf(i + chunk, text.length)
        // Never split a surrogate pair across two literals.
        if (end < text.length && text[end - 1].isHighSurrogate()) end--
        out.append("        \"")
        for (c in text.substring(i, end)) {
            when {
                c == '\\' -> out.append("\\\\")
                c == '"' -> out.append("\\\"")
                c == '$' -> out.append("\\$")
                c == '\n' -> out.append("\\n")
                c == '\r' -> out.append("\\r")
                c == '\t' -> out.append("\\t")
                c.code < 0x20 || c.code > 0x7e -> out.append("\\u").append(c.code.toString(16).padStart(4, '0'))
                else -> out.append(c)
            }
        }
        out.append("\",\n")
        i = end
    }
    return out.toString()
}

val generatePslEmbedded by tasks.registering {
    val dat = pslDir.file("public_suffix_list.dat")
    val sha = pslDir.file("public_suffix_list.dat.sha256")
    val outDir = layout.buildDirectory.dir("generated/pslEmbedded/kotlin")
    inputs.files(dat, sha)
    outputs.dir(outDir)
    doLast {
        val text = dat.asFile.readText(Charsets.UTF_8)
        val recorded = sha.asFile.readText(Charsets.UTF_8)
        val file = outDir.get().file("dev/loupe/engine/PslEmbedded.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            "// GENERATED by :engine:generatePslEmbedded from public_suffix_list.dat. Do not edit.\n" +
                "package dev.loupe.engine\n\n" +
                "internal object PslEmbedded {\n" +
                "    val SHA256_FILE: String = " + kotlinStringChunks(recorded).trim().removeSuffix(",") + "\n\n" +
                "    val CHUNKS: Array<String> = arrayOf(\n" + kotlinStringChunks(text) + "    )\n" +
                "}\n",
        )
    }
}

val generatePslTestVectors by tasks.registering {
    val src = layout.projectDirectory.file("src/jvmTest/resources/dev/loupe/engine/psl_tests.txt")
    val outDir = layout.buildDirectory.dir("generated/pslTestVectors/kotlin")
    inputs.file(src)
    outputs.dir(outDir)
    doLast {
        val file = outDir.get().file("dev/loupe/engine/PslTestVectors.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            "// GENERATED by :engine:generatePslTestVectors from psl_tests.txt. Do not edit.\n" +
                "package dev.loupe.engine\n\n" +
                "internal object PslTestVectors {\n" +
                "    val TEXT: String = arrayOf(\n" + kotlinStringChunks(src.asFile.readText(Charsets.UTF_8)) +
                "    ).joinToString(\"\")\n}\n",
        )
    }
}

// iOS targets are declared only on macOS: Kotlin/Native cannot build Apple targets elsewhere, and
// declaring them on Linux CI would only produce "disabled target" noise. JVM tests run everywhere.
val appleHost = System.getProperty("os.name").startsWith("Mac")

kotlin {
    jvm {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_21)
        }
    }
    if (androidHost) {
        androidTarget {
            compilerOptions {
                jvmTarget.set(JvmTarget.JVM_17)
            }
        }
    }
    if (appleHost) {
        iosArm64()
        iosSimulatorArm64()
    }

    applyDefaultHierarchyTemplate()

    sourceSets {
        commonMain.dependencies {
            // The one third-party dependency: calendar dates without java.time. Kotlin team,
            // Apache-2.0. 0.6.1 is the last line built against Kotlin 2.1.0 (docs/BUILD.md Traps).
            api("org.jetbrains.kotlinx:kotlinx-datetime:0.6.1")
        }
        commonTest {
            // The PSL test vectors, as a generated Kotlin constant so iOS tests can read them.
            kotlin.srcDir(generatePslTestVectors)
            dependencies {
                implementation(kotlin("test"))
            }
        }
        jvmTest.dependencies {
            implementation("org.junit.jupiter:junit-jupiter:5.11.4")
            runtimeOnly("org.junit.platform:junit-platform-launcher")
        }
        if (appleHost) {
            iosMain {
                // The bundled PSL snapshot and its recorded SHA-256, embedded as generated Kotlin.
                kotlin.srcDir(generatePslEmbedded)
            }
        }
        if (androidHost) {
            androidMain {
                // Android takes the same embedded snapshot as iOS: no classpath resource lookup in
                // the APK, and the bytes are the very file the JVM reads.
                kotlin.srcDir(generatePslEmbedded)
            }
        }
    }
}

if (androidHost) {
    extensions.configure<com.android.build.api.dsl.LibraryExtension> {
        namespace = "dev.loupe.engine"
        compileSdk = 36
        defaultConfig {
            minSdk = 29
        }
        compileOptions {
            sourceCompatibility = JavaVersion.VERSION_17
            targetCompatibility = JavaVersion.VERSION_17
        }
    }
}

tasks.named<Test>("jvmTest") {
    useJUnitPlatform()
}

// ---- Cross-platform regex parity (docs/ANDROID-PLAN.md, "Known parity gaps", B1) ----------------
//
// Shared main sources must not use regex classes or case folding whose meaning differs between the
// JDK, Kotlin/Native and Android's ICU; tools/android-regex-check/lint.py fails the build when they
// do (with an allowlist that needs a justification per entry). Its tests and the regex extractor's
// run with it. Needs python3 (3.9+), as the other repo tools do. Part of `check` on every host.
val regexToolDir = rootProject.file("tools/android-regex-check")
val sharedMainSources = rootProject.fileTree(rootProject.projectDir) {
    listOf("engine", "templates", "persistence", "sources-common", "game", "backend-laya-common", "loupe-kit").forEach { m ->
        listOf("commonMain", "jvmCommonMain", "jvmMain", "androidMain", "iosMain").forEach { s -> include("$m/src/$s/**/*.kt") }
    }
}
fun registerPython(name: String, script: String, what: String) = tasks.register<Exec>(name) {
    group = "verification"
    description = what
    workingDir = rootProject.projectDir
    commandLine("python3", "tools/android-regex-check/$script")
    inputs.files(sharedMainSources)
    inputs.files(rootProject.fileTree(regexToolDir) { exclude("**/__pycache__/**") }).withPropertyName("tool")
    val marker = layout.buildDirectory.file("verification/$name.ok")
    outputs.file(marker)
    doLast { marker.get().asFile.apply { parentFile.mkdirs(); writeText("ok\n") } }
}
val portableRegexLint = registerPython("portableRegexLint", "lint.py", "No engine-defined regex classes or case folding in shared main sources")
val portableRegexLintTests = registerPython("portableRegexLintTests", "test_lint.py", "Tests of the portable regex lint")
val regexExtractorTests = registerPython("regexExtractorTests", "test_extract.py", "Tests of the Android regex extractor")
tasks.named("check") {
    dependsOn(portableRegexLint, portableRegexLintTests, regexExtractorTests)
}
