import Foundation

/// The Web tab library's words, English and Arabic. Arabic follows the phone's language (or
/// `-LoupeLanguage ar`), as Model settings and the live run view do.
enum WS {
    static func t(_ key: String, _ args: [String: String] = [:]) -> String {
        let pair = table[key]
        var s = (MS.lang == .ar ? pair?.1 : pair?.0) ?? pair?.0 ?? key
        for (k, v) in args { s = s.replacingOccurrences(of: "{\(k)}", with: v) }
        return s
    }

    static let table: [String: (String, String)] = [
        "library.title": ("Ask the web", "اسأل الويب"),
        "library.intro": ("Pick a template, then a ready-made question or your own. Loupe fetches the data online and answers on this phone.",
                          "اختر قالبًا، ثم سؤالًا جاهزًا أو سؤالك الخاص. يجلب Loupe البيانات عبر الإنترنت ويجيب على هذا الهاتف."),
        "sector.currency": ("Currency", "العملات"),
        "sector.weather": ("Weather", "الطقس"),
        "sector.trains": ("UK trains", "قطارات بريطانيا"),
        "sector.flights": ("Flights", "الرحلات الجوية"),
        "provider.currency": ("Frankfurter", "Frankfurter"),
        "provider.weather": ("Open-Meteo", "Open-Meteo"),
        "provider.trains": ("National Rail", "National Rail"),
        "provider.flights": ("Duffel", "Duffel"),
        "sends.currency": ("Only the currency codes and dates are sent.", "تُرسَل رموز العملات والتواريخ فقط."),
        "sends.weather": ("Only the place name is sent.", "يُرسَل اسم المكان فقط."),
        "sends.trains": ("Only the two station codes are sent.", "يُرسَل رمزا المحطتين فقط."),
        "sends.flights": ("The route, dates and your own Duffel key are sent.", "يُرسَل المسار والتواريخ ومفتاح Duffel الخاص بك."),
        "flights.devOnly": ("Development only — pending provider permission", "للتطوير فقط — بانتظار إذن المزوّد"),
        "off": ("Off", "متوقف"),
        "source.off": ("{sector} is off", "{sector} متوقف"),
        "source.offText": ("Turn it on to fetch from {provider} through Loupe's helper. {sends} Nothing else leaves the phone.",
                           "شغّله لجلب البيانات من {provider} عبر مساعد Loupe. {sends} لا يغادر الهاتف شيء آخر."),
        "source.turnOn": ("Turn on {sector} (online)", "تشغيل {sector} (عبر الإنترنت)"),
        "source.toggle": ("{sector} (online)", "{sector} (عبر الإنترنت)"),
        "questions": ("Questions", "الأسئلة"),
        "custom": ("Your own question", "سؤالك الخاص"),
        "custom.placeholder": ("Ask about each item, e.g. Is this day warm enough to swim", "اسأل عن كل عنصر، مثلًا: هل هذا اليوم دافئ بما يكفي للسباحة"),
        "custom.type": ("Decision type", "نوع القرار"),
        "custom.ok": ("Laya can answer this on the phone.", "يستطيع Laya الإجابة عن هذا على الهاتف."),
        "type.yes_no": ("Yes / no", "نعم / لا"),
        "type.pick": ("Pick the best", "اختر الأفضل"),
        "type.score": ("Score", "تقييم"),
        "type.rank": ("Rank the list", "رتّب القائمة"),
        "ask": ("Ask", "اسأل"),
        "asking": ("Fetching…", "جارٍ الجلب…"),
        "online": ("Online · {provider} · fetched {time}", "عبر الإنترنت · {provider} · جُلب {time}"),
        "fixture": ("Fixture data (development build): not live.", "بيانات تجريبية (نسخة تطوير): ليست حية."),
        "answer.laya": ("Laya (on this phone)", "Laya (على هذا الهاتف)"),
        "answer.rules": ("Rules", "القواعد"),
        "answer.by": ("Answered by: {who}", "أجاب: {who}"),
        "answer.showRules": ("View the rule answer", "عرض إجابة القواعد"),
        "answer.pick": ("{who} picks: {item}", "اختيار {who}: {item}"),
        "answer.top": ("{who} #1: {item}", "الأول عند {who}: {item}"),
        "answer.yesno": ("{who}: {answer} — {item}", "{who}: {answer} — {item}"),
        "answer.scored": ("{who} scored {n} items", "قيّم {who} عناصر عددها {n}"),
        "answer.agree": ("Laya and the rules agree.", "يتفق Laya والقواعد."),
        "answer.disagree": ("Laya and the rules disagree: the rules say {rules}.", "يختلف Laya والقواعد: تقول القواعد {rules}."),
        "answer.unsure": ("Laya is unsure about {n} of these, marked below. Its percentages are not yet calibrated to your corrections.",
                          "Laya غير متأكد من {n} منها، وهي معلّمة أدناه. نسبه لم تُعايَر بعد على تصحيحاتك."),
        "answer.sure": ("Laya is sure of every answer here. Its percentages are not yet calibrated to your corrections.",
                        "Laya متأكد من كل إجابة هنا. نسبه لم تُعايَر بعد على تصحيحاتك."),
        "answer.running": ("Laya is reading item {i} of {n}, on this phone", "يقرأ Laya العنصر {i} من {n}، على هذا الهاتف"),
        "answer.runningRules": ("Showing the rule answer until Laya is done.", "تُعرض إجابة القواعد حتى ينتهي Laya."),
        "answer.cancel": ("Cancel", "إلغاء"),
        "answer.cancelled": ("Laya cancelled; showing the rules.", "أُلغي Laya؛ تُعرض القواعد."),
        "answer.retry": ("Answer with Laya", "أجب باستخدام Laya"),
        "answer.customRule": ("Custom question: the rules can't read it, so they show the {sector} default ({rule}).",
                              "سؤال خاص: لا تستطيع القواعد قراءته، فتعرض الافتراضي لـ{sector} ({rule})."),
        "rulesOnly.notInstalled": ("Rules only: the on-device model is not on this phone yet.", "القواعد فقط: النموذج غير موجود على هذا الهاتف بعد."),
        "rulesOnly.failed": ("Rules only: the on-device model could not be used ({m}).", "القواعد فقط: تعذّر استخدام النموذج ({m})."),
        "rulesOnly.refused": ("Rules only: Laya cannot answer this question ({m}).", "القواعد فقط: لا يستطيع Laya الإجابة عن هذا السؤال ({m})."),
        "rulesOnly.off": ("Rules only: Laya is off for the Web tab in Model settings.", "القواعد فقط: Laya متوقف لتبويب الويب في إعدادات النموذج."),
        "getModel": ("Get the on-device model", "احصل على النموذج"),
        "row.source": ("Source: {item}", "المصدر: {item}"),
        "row.open": ("Open at {provider}", "فتح لدى {provider}"),
        "row.unsure": ("unsure", "غير متأكد"),
        "yes": ("yes", "نعم"),
        "no": ("no", "لا"),
        "notConfigured.weather": ("Weather needs Loupe's commercial Open-Meteo plan — not set up yet. Nothing was fetched.",
                                  "يحتاج الطقس إلى خطة Open-Meteo التجارية لـ Loupe — لم تُجهَّز بعد. لم يُجلب شيء."),
        "notConfigured.trains": ("UK trains needs Loupe's National Rail data key — not set up yet. Nothing was fetched.",
                                 "تحتاج قطارات بريطانيا إلى مفتاح بيانات National Rail لـ Loupe — لم يُجهَّز بعد. لم يُجلب شيء."),
        "notConfigured.currency": ("Currency is not set up on Loupe's helper yet. Nothing was fetched.",
                                   "العملات غير مُجهّزة على مساعد Loupe بعد. لم يُجلب شيء."),
        "notDeployed": ("{sector} is not available yet: Loupe's online helper does not offer it yet. Nothing was fetched.",
                        "{sector} غير متاح بعد: مساعد Loupe على الإنترنت لا يقدّمه بعد. لم يُجلب شيء."),
        "noRows": ("The source sent nothing to judge for these inputs.", "لم يرسل المصدر شيئًا للحكم عليه لهذه المدخلات."),
        "input.base": ("From", "من"),
        "input.quote": ("To", "إلى"),
        "input.home": ("Home currency", "عملتك"),
        "input.basket": ("Currencies to rank", "العملات للترتيب"),
        "input.place": ("Place", "المكان"),
        "input.from": ("From station (CRS)", "محطة المغادرة"),
        "input.to": ("To station (CRS)", "محطة الوصول"),
        "input.by": ("Arrive by", "الوصول قبل"),
        "input.journey": ("Journey: {m} min", "مدة الرحلة: {m} دقيقة"),
        "input.target": ("Train at", "قطار الساعة"),
        "input.badCurrency": ("Use 3-letter currency codes, like EUR or EGP.", "استخدم رموز عملات من 3 أحرف، مثل EUR أو EGP."),
        "input.sameCurrency": ("From and To are the same currency.", "العملتان متطابقتان."),
        "input.badPlace": ("Write a place name.", "اكتب اسم مكان."),
        "input.badCrs": ("Use 3-letter station codes, like PAD or RDG.", "استخدم رموز محطات من 3 أحرف، مثل PAD أو RDG."),
        "input.badTime": ("Times look like 08:15.", "تُكتب الأوقات مثل 08:15."),
        "attribution.providers": ("Rate providers", "مزوّدو الأسعار"),
        "privacy": ("Only the search leaves the phone. The question, the answers and your ledger stay here.",
                    "لا يغادر الهاتف سوى البحث. يبقى السؤال والإجابات وسجلك هنا."),
        "rule.rate": ("rate {v}", "السعر {v}"),
        "rule.weekHigh": ("the week's highest rate", "أعلى سعر هذا الأسبوع"),
        "rule.belowHigh": ("below the week's high {v}", "أقل من أعلى سعر {v}"),
        "rule.aboveAvg": ("above the average {v}", "أعلى من المتوسط {v}"),
        "rule.belowAvg": ("not above the average {v}", "ليس أعلى من المتوسط {v}"),
        "rule.noAverage": ("too few days for an average", "أيام قليلة لحساب متوسط"),
        "rule.dry": ("dry ({p} rain)", "جاف ({p} مطر)"),
        "rule.wet": ("not dry ({p} rain)", "غير جاف ({p} مطر)"),
        "rule.notSaturday": ("not Saturday", "ليس السبت"),
        "rule.warmDry": ("high {t}°, warm and dry scores best", "العظمى {t}°، الدافئ والجاف أفضل"),
        "rule.morning": ("morning low {t}°", "صغرى الصباح {t}°"),
        "rule.mildDry": ("high {t}°, mild and dry scores best", "العظمى {t}°، المعتدل والجاف أفضل"),
        "rule.umbrella": ("rain likely ({p})", "المطر مرجّح ({p})"),
        "rule.noUmbrella": ("rain unlikely ({p})", "المطر غير مرجّح ({p})"),
        "rule.arrivesBy": ("arrives about {t}", "يصل نحو {t}"),
        "rule.arrivesLate": ("arrives about {t}, too late", "يصل نحو {t}، متأخر"),
        "rule.notTarget": ("not that train", "ليس ذلك القطار"),
        "rule.cancelled": ("cancelled", "ملغى"),
        "rule.onTime": ("on time", "في الموعد"),
        "rule.late": ("{m} min late", "متأخر {m} دقيقة"),
        "rule.delayedUnknown": ("delayed, no time given", "متأخر، دون وقت"),
        "rule.name.highestRate": ("highest rate first", "الأعلى سعرًا أولًا"),
        "rule.name.picnic": ("mild and dry days first", "الأيام المعتدلة والجافة أولًا"),
        "rule.name.reliability": ("on time, then earlier", "في الموعد، ثم الأبكر"),
        "wx.clear": ("clear", "صافٍ"),
        "wx.partly": ("partly cloudy", "غائم جزئيًا"),
        "wx.overcast": ("overcast", "ملبّد"),
        "wx.fog": ("fog", "ضباب"),
        "wx.drizzle": ("drizzle", "رذاذ"),
        "wx.rain": ("rain", "مطر"),
        "wx.snow": ("snow", "ثلج"),
        "wx.storm": ("thunderstorm", "عاصفة رعدية"),
        "wx.unknown": ("not stated", "غير مذكور"),
    ]
}
