import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    kotlin("multiplatform")
    // Loupe for Android (docs/ANDROID-PLAN.md): an Android library target beside JVM and iOS.
    id("com.android.library")
}

repositories {
    mavenCentral()
    google()
}

// Sources in common code (epic #7 child 2): the SourceItem model, the pure-Kotlin extractors (text,
// Markdown, CSV, JSON, HTML, email and mbox through a small common MIME parser) and a scanner that
// matches :sources-desktop item for item. PDF text and image metadata are the platform's: the host
// passes a PlatformExtractors (PDFKit/ImageIO from Swift on iOS; PDFBox/metadata-extractor in
// :sources-desktop on the JVM). No third-party code.
val appleHost = System.getProperty("os.name").startsWith("Mac")

// Kotlin/Native tests have no classpath resources; they read the sample from the repo by path. The
// iOS simulator shares the host file system, so the absolute path works there too.
val sampleDir = rootProject.file("sources-desktop/src/main/resources/dev/loupe/sources/sample")
val generateTestPaths by tasks.registering {
    val outDir = layout.buildDirectory.dir("generated/testPaths/kotlin")
    inputs.property("sample", sampleDir.absolutePath)
    outputs.dir(outDir)
    doLast {
        val f = outDir.get().file("dev/loupe/sources/common/TestPaths.kt").asFile
        f.parentFile.mkdirs()
        f.writeText(
            "// GENERATED by :sources-common:generateTestPaths. Do not edit.\n" +
                "package dev.loupe.sources.common\n\n" +
                "internal const val SAMPLE_DIR: String = \"" + sampleDir.absolutePath.replace("\\", "/") + "\"\n",
        )
    }
}

kotlin {
    compilerOptions { freeCompilerArgs.add("-Xexpect-actual-classes") }
    jvm {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_21)
        }
    }
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }
    if (appleHost) {
        iosArm64()
        iosSimulatorArm64()
    }

    // jvmCommon: the JVM actuals, shared as is by the desktop JVM and Android (docs/ANDROID-PLAN.md,
    // "no logic forks"). Written against APIs Android has at minSdk 29.
    @OptIn(org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi::class)
    applyDefaultHierarchyTemplate {
        common {
            group("jvmCommon") {
                withJvm()
                withAndroidTarget()
            }
        }
    }

    sourceSets {
        all { languageSettings.optIn("kotlin.io.encoding.ExperimentalEncodingApi") }
        commonMain.dependencies {
            api(project(":engine"))
            api(project(":persistence"))
        }
        commonTest {
            kotlin.srcDir(generateTestPaths)
            dependencies {
                implementation(kotlin("test"))
            }
        }
        jvmTest.dependencies {
            implementation("org.junit.jupiter:junit-jupiter:5.11.4")
            runtimeOnly("org.junit.platform:junit-platform-launcher")
        }
    }
}

android {
    namespace = "dev.loupe.sources.common"
    compileSdk = 36
    defaultConfig {
        minSdk = 29
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

tasks.named<Test>("jvmTest") {
    useJUnitPlatform()
}
