// Regenerates engine/src/commonMain/kotlin/dev/loupe/engine/UnicodeScriptTable.kt from the running
// JDK's Character.UnicodeScript data. Run from the repo root with the build JDK (21):
//
//   java tools/GenUnicodeScripts.java > engine/src/commonMain/kotlin/dev/loupe/engine/UnicodeScriptTable.kt
//
// The table maps every code point to the ordinal of its Character.UnicodeScript when it is a letter
// of a real script, and to -1 otherwise (not a letter, or COMMON / INHERITED). The JVM keeps using
// the JDK directly; iOS reads this table; a jvmTest checks the two agree on every code point.
public class GenUnicodeScripts {
    public static void main(String[] args) {
        StringBuilder runs = new StringBuilder();
        int prev = Integer.MIN_VALUE;
        int count = 0;
        for (int cp = 0; cp <= Character.MAX_CODE_POINT; cp++) {
            int id = -1;
            if (Character.isLetter(cp)) {
                Character.UnicodeScript s = Character.UnicodeScript.of(cp);
                if (s != Character.UnicodeScript.COMMON && s != Character.UnicodeScript.INHERITED) id = s.ordinal();
            }
            if (id != prev) {
                runs.append(Integer.toString(cp, 36)).append(':').append(Integer.toString(id + 1, 36)).append(';');
                prev = id;
                count++;
            }
        }
        String all = runs.toString();
        StringBuilder out = new StringBuilder();
        out.append("// GENERATED by tools/GenUnicodeScripts.java from JDK ").append(System.getProperty("java.version"))
           .append(" Character.UnicodeScript (Unicode ").append("data of that JDK). Do not edit.\n");
        out.append("package dev.loupe.engine\n\n");
        out.append("/** ").append(count).append(" runs of `start:scriptOrdinal+1;` in base 36; 0 means no script. */\n");
        out.append("internal object UnicodeScriptTable {\n");
        out.append("    const val JDK_VERSION: String = \"").append(System.getProperty("java.version")).append("\"\n\n");
        out.append("    val RUNS: String = arrayOf(\n");
        for (int i = 0; i < all.length(); i += 8000) {
            out.append("        \"").append(all, i, Math.min(all.length(), i + 8000)).append("\",\n");
        }
        out.append("    ).joinToString(\"\")\n}\n");
        System.out.print(out);
    }
}
