#!/usr/bin/env python3
"""
Tokenizer parity fixture (issue #8): the Laya reference package's own tokenizer (laya 0.3.20,
`laya.agent._load_tokenizer`, the one `build_sequence` calls) encodes a set of English, Arabic,
Egyptian Arabic, Franco-Arabic (Arabizi), Spanish and French strings. The JVM (DJL) and iOS
(tokenizers-ffi) tests must reproduce every id list exactly.

    USE_TF=0 tools/.venv/bin/python tools/make-laya-tokenizer-fixture.py
"""
import json
import os
from pathlib import Path

os.environ.setdefault("USE_TF", "0")
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")

ROOT = Path(__file__).resolve().parent.parent
LAYA_COMMIT = "23a17522aa4942da6cce53a995a275760320b691"

STRINGS = [
    ("en", "Can you send me the slides from Tuesday's meeting before Friday?"),
    ("en", "URGENT: your account will be suspended — verify at https://examp1e-bank.co/login now!!"),
    ("en", "Receipt #A-1029 · Total £12.40 (incl. VAT 20%) — thanks for shopping 🛒"),
    ("en", "  leading and trailing spaces\tand a tab\nand a newline  "),
    ("ar", "هل يمكنك إرسال الشرائح من اجتماع الثلاثاء قبل يوم الجمعة؟"),
    ("ar", "تم خصم ١٢٫٤٠ ريال من بطاقتك المنتهية بـ ٤٤٢١. إذا لم تقم بهذه العملية اتصل بنا فورًا."),
    ("ar", "فاتورة رقم 2051 — المبلغ الإجمالي: 553.50 جنيه"),
    ("arz", "لو سمحت ابعتلي الملف النهارده ضروري عشان المدير مستني"),
    ("arz", "إزيك يا باشا؟ الحساب بتاعك هيتقفل لو ما دخلتش على اللينك ده"),
    ("arz", "انا زهقت من التأخير ده بجد، الطلب بقاله أسبوعين ماوصلش"),
    ("franco", "ezayak ya basha? 3amel eh enaharda?"),
    ("franco", "law sama7t ab3atly el file ennaharda 3ashan el modeer mestany"),
    ("franco", "el 7esab beta3ak hayet2efel law ma da5altsh 3ala el link da"),
    ("franco", "ana 3ayez a2abel 7adretak bokra el sa3a 5"),
    ("es", "¿Puedes enviarme las diapositivas de la reunión del martes antes del viernes?"),
    ("es", "Su cuenta será suspendida. Verifique sus datos aquí: añadir contraseña ñandú"),
    ("fr", "Pouvez-vous m'envoyer les diapositives de la réunion de mardi avant vendredi ?"),
    ("fr", "Votre colis est bloqué à la douane : réglez 2,99 € ici — c'est très urgent."),
    ("mixed", "Meeting غدًا at 10am — la réunion est à 10h, ya3ni bokra"),
    ("mixed", "choice question: How urgent is the request in `email`?"),
    ("mixed", " level 0: blocking problem or due today"),
]


def main():
    from laya.agent import _load_tokenizer
    import laya

    model_dir = ROOT / "models/laya-multilingual"
    cfg = json.load(open(model_dir / "rl_agent_config.json"))
    tok = _load_tokenizer(str(model_dir / "tokenizer"), cfg)
    cases = [{"lang": lang, "text": t, "ids": tok(t, add_special_tokens=False)["input_ids"]} for lang, t in STRINGS]
    out = {
        "_comment": "Generated by tools/make-laya-tokenizer-fixture.py. Do not edit by hand.",
        "laya_version": laya.__version__,
        "laya_commit": LAYA_COMMIT,
        "cases": cases,
    }
    path = ROOT / "backend-onnx/src/test/resources/laya/tokenizer.json"
    path.write_text(json.dumps(out, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print("wrote %s (%d strings)" % (path, len(cases)))


if __name__ == "__main__":
    main()
