import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework

plugins {
    kotlin("multiplatform")
}

repositories {
    mavenCentral()
}

// LoupeKit: the iOS-facing umbrella over :engine, :templates and :game, shipped as one XCFramework.
// `./gradlew :loupe-kit:assembleLoupeKitXCFramework` (macOS only; see docs/BUILD.md).
val appleHost = System.getProperty("os.name").startsWith("Mac")
// Laya on iOS (ORT + the Rust tokenizer) is exported when settings.gradle.kts included it, i.e. once
// ios-native/build.sh has run. Without it LoupeKit builds as before and the app cannot link Laya.
val layaIos = rootProject.findProject(":backend-onnx-ios")

// Kotlin/Native tests have no classpath resources; the watcher tests read the shipped sample from
// the repo by path (the iOS simulator shares the host file system), as :sources-common's do.
val sampleDir = rootProject.file("sources-desktop/src/main/resources/dev/loupe/sources/sample")
val examplePack = rootProject.file("examples/packs/bistro-cloud.json")
// The shared phishing formula's test vectors (docs/PHISHING-FORMULA.md), run on the JVM and the iOS simulator.
val phishingVectors = rootProject.file("docs/phishing-vectors.json")
// Formula v1.2 vectors (docs/PHISHING-FORMULA.md §5b–§6.1) and the Phishing.Database samples (copied from
// Loupe Station's tests/fixtures/phishingdb with their NOTICE), both read by tests only, never shipped.
val phishingVectorsV12 = rootProject.file("docs/phishing-vectors-v1.2.json")
val phishingDbFixtures = project.file("src/commonTest/fixtures/phishingdb")
// Fast Decisions (fastino/fast-decisions, Apache-2.0): the trimmed sample the parser tests read.
// The full 1.9 MB development split is fetched, never committed -- tools/fetch-fast-decisions.sh.
val fastDecisionsSample = project.file("src/commonTest/fixtures/fast-decisions/sample.jsonl")
// shared_hosts.json: copied verbatim from Loupe Station (laya_studio/online/shared_hosts.json, commit
// 4cb9026). It is the one source of the list: generateSharedHosts turns it into commonMain Kotlin.
val sharedHostsJson = project.file("data/shared_hosts.json")
val generateSharedHosts by tasks.registering {
    val outDir = layout.buildDirectory.dir("generated/sharedHosts/kotlin")
    inputs.file(sharedHostsJson)
    outputs.dir(outDir)
    doLast {
        val text = sharedHostsJson.readText()
        val body = Regex("\"hosts\"\\s*:\\s*\\[([^\\]]*)\\]").find(text)?.groupValues?.get(1)
            ?: error("shared_hosts.json: no hosts array")
        val hosts = Regex("\"([^\"]+)\"").findAll(body).map { it.groupValues[1].trim().lowercase() }.filter { it.isNotEmpty() }.toList()
        require(hosts.size >= 50) { "shared_hosts.json: only ${hosts.size} hosts" }
        val version = Regex("\"version\"\\s*:\\s*(\\d+)").find(text)?.groupValues?.get(1) ?: "0"
        val updated = Regex("\"updated\"\\s*:\\s*\"([^\"]*)\"").find(text)?.groupValues?.get(1) ?: ""
        val f = outDir.get().file("dev/loupe/kit/site/SharedHostsData.kt").asFile
        f.parentFile.mkdirs()
        f.writeText(
            "// GENERATED by :loupe-kit:generateSharedHosts from loupe-kit/data/shared_hosts.json. Do not edit.\n" +
                "package dev.loupe.kit.site\n\n" +
                "internal object SharedHostsData {\n" +
                "    const val VERSION: Int = " + version + "\n" +
                "    const val UPDATED: String = \"" + updated + "\"\n" +
                "    val HOSTS: List<String> = listOf(\n" +
                hosts.joinToString("") { "        \"" + it + "\",\n" } +
                "    )\n}\n",
        )
    }
}
val generateTestPaths by tasks.registering {
    val outDir = layout.buildDirectory.dir("generated/testPaths/kotlin")
    inputs.property("sample", sampleDir.absolutePath)
    inputs.property("examplePack", examplePack.absolutePath)
    inputs.property("phishingVectors", phishingVectors.absolutePath)
    inputs.property("phishingVectorsV12", phishingVectorsV12.absolutePath)
    inputs.property("phishingDbFixtures", phishingDbFixtures.absolutePath)
    inputs.property("sharedHostsJson", sharedHostsJson.absolutePath)
    inputs.property("fastDecisionsSample", fastDecisionsSample.absolutePath)
    val scratch = layout.buildDirectory.dir("tmp/kit-tests").get().asFile.absolutePath
    inputs.property("scratch", scratch)
    outputs.dir(outDir)
    doLast {
        val f = outDir.get().file("dev/loupe/kit/watchers/TestPaths.kt").asFile
        f.parentFile.mkdirs()
        f.writeText(
            "// GENERATED by :loupe-kit:generateTestPaths. Do not edit.\n" +
                "package dev.loupe.kit.watchers\n\n" +
                "internal const val SAMPLE_DIR: String = \"" + sampleDir.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val EXAMPLE_PACK: String = \"" + examplePack.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val PHISHING_VECTORS: String = \"" + phishingVectors.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val PHISHING_VECTORS_V12: String = \"" + phishingVectorsV12.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val PHISHINGDB_FIXTURES: String = \"" + phishingDbFixtures.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val SHARED_HOSTS_JSON: String = \"" + sharedHostsJson.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val FAST_DECISIONS_SAMPLE: String = \"" + fastDecisionsSample.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val TEST_TMP: String = \"" + scratch.replace("\\", "/") + "\"\n",
        )
    }
}

kotlin {
    // A JVM target keeps the module an ordinary participant in `./gradlew build` on Linux CI.
    jvm()

    if (appleHost) {
        val xcf = XCFramework("LoupeKit")
        listOf(iosArm64(), iosSimulatorArm64()).forEach { target ->
            target.binaries.framework {
                baseName = "LoupeKit"
                isStatic = true
                export(project(":engine"))
                export(project(":templates"))
                export(project(":game"))
                export(project(":persistence"))
                export(project(":sources-common"))
                if (layaIos != null) {
                    export(layaIos)
                    export(project(":backend-laya-common"))
                }
                xcf.add(this)
            }
        }
    }

    applyDefaultHierarchyTemplate()

    sourceSets {
        commonMain {
            kotlin.srcDir(generateSharedHosts)
        }
        commonMain.dependencies {
            api(project(":engine"))
            api(project(":templates"))
            // The game (Riverflight) for the iPhone app: rules, pilots, GameSessions, HostedDecider.
            api(project(":game"))
            // The ledger on the phone (epic #7 child 1): PhoneLedger, the files, the F4 export.
            api(project(":persistence"))
            // Sources on the phone (epic #7 child 2): SourceItem, the common extractors and scanner, the cache.
            api(project(":sources-common"))
        }
        commonTest {
            kotlin.srcDir(generateTestPaths)
            dependencies {
                implementation(kotlin("test"))
            }
        }
        // The sample's PDFs need a real reader: PDFBox (through :sources-desktop) on the JVM,
        // PDFKit on the iOS simulator — the readers each app uses.
        jvmTest.dependencies {
            implementation(project(":sources-desktop"))
        }
        if (appleHost && layaIos != null) {
            iosMain {
                // Only compiled when Laya for iOS is present, since it calls into it.
                kotlin.srcDir("src/iosLaya/kotlin")
                dependencies {
                    api(layaIos)
                    api(project(":backend-laya-common"))
                }
            }
        }
    }
}

// Scores the Fast Decisions development split. With no backend it runs the two reference
// predictors (the oracle majority prior and the label-name baseline), which need no model and give
// every published figure a floor to sit on:
//
//   tools/fetch-fast-decisions.sh && ./gradlew :loupe-kit:fastDecisions
//
// Pass a directory with --args if the data is somewhere else.
tasks.register<JavaExec>("fastDecisions") {
    group = "verification"
    description = "Scores the Fast Decisions development split (baselines only without a backend)."
    mainClass.set("dev.loupe.kit.measure.FastDecisionsMain")
    classpath = kotlin.targets.getByName("jvm").compilations.getByName("main").output.allOutputs +
        configurations.getByName("jvmRuntimeClasspath")
}
