import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework

plugins {
    kotlin("multiplatform")
}

repositories {
    mavenCentral()
}

// LoupeKit: the iOS-facing umbrella over :engine, :templates and :game, shipped as one XCFramework.
// `./gradlew :loupe-kit:assembleLoupeKitXCFramework` (macOS only; see docs/BUILD.md).
val appleHost = System.getProperty("os.name").startsWith("Mac")
// Laya on iOS (ORT + the Rust tokenizer) is exported when settings.gradle.kts included it, i.e. once
// ios-native/build.sh has run. Without it LoupeKit builds as before and the app cannot link Laya.
val layaIos = rootProject.findProject(":backend-onnx-ios")

// Kotlin/Native tests have no classpath resources; the watcher tests read the shipped sample from
// the repo by path (the iOS simulator shares the host file system), as :sources-common's do.
val sampleDir = rootProject.file("sources-desktop/src/main/resources/dev/loupe/sources/sample")
val generateTestPaths by tasks.registering {
    val outDir = layout.buildDirectory.dir("generated/testPaths/kotlin")
    inputs.property("sample", sampleDir.absolutePath)
    outputs.dir(outDir)
    doLast {
        val f = outDir.get().file("dev/loupe/kit/watchers/TestPaths.kt").asFile
        f.parentFile.mkdirs()
        f.writeText(
            "// GENERATED by :loupe-kit:generateTestPaths. Do not edit.\n" +
                "package dev.loupe.kit.watchers\n\n" +
                "internal const val SAMPLE_DIR: String = \"" + sampleDir.absolutePath.replace("\\", "/") + "\"\n",
        )
    }
}

kotlin {
    // A JVM target keeps the module an ordinary participant in `./gradlew build` on Linux CI.
    jvm()

    if (appleHost) {
        val xcf = XCFramework("LoupeKit")
        listOf(iosArm64(), iosSimulatorArm64()).forEach { target ->
            target.binaries.framework {
                baseName = "LoupeKit"
                isStatic = true
                export(project(":engine"))
                export(project(":templates"))
                export(project(":game"))
                export(project(":persistence"))
                export(project(":sources-common"))
                if (layaIos != null) {
                    export(layaIos)
                    export(project(":backend-laya-common"))
                }
                xcf.add(this)
            }
        }
    }

    applyDefaultHierarchyTemplate()

    sourceSets {
        commonMain.dependencies {
            api(project(":engine"))
            api(project(":templates"))
            // The game (Riverflight) for the iPhone app: rules, pilots, GameSessions, HostedDecider.
            api(project(":game"))
            // The ledger on the phone (epic #7 child 1): PhoneLedger, the files, the F4 export.
            api(project(":persistence"))
            // Sources on the phone (epic #7 child 2): SourceItem, the common extractors and scanner, the cache.
            api(project(":sources-common"))
        }
        commonTest {
            kotlin.srcDir(generateTestPaths)
            dependencies {
                implementation(kotlin("test"))
            }
        }
        // The sample's PDFs need a real reader: PDFBox (through :sources-desktop) on the JVM,
        // PDFKit on the iOS simulator — the readers each app uses.
        jvmTest.dependencies {
            implementation(project(":sources-desktop"))
        }
        if (appleHost && layaIos != null) {
            iosMain {
                // Only compiled when Laya for iOS is present, since it calls into it.
                kotlin.srcDir("src/iosLaya/kotlin")
                dependencies {
                    api(layaIos)
                    api(project(":backend-laya-common"))
                }
            }
        }
    }
}
