import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework

plugins {
    kotlin("multiplatform")
}

// Loupe for Android (docs/ANDROID-PLAN.md): an Android library target beside JVM and iOS, only where
// settings.gradle.kts found an Android SDK (it says so when it did not).
val androidHost = gradle.extra["loupe.android"] as Boolean
if (androidHost) apply(plugin = "com.android.library")

repositories {
    mavenCentral()
    google()
}

// LoupeKit: the iOS-facing umbrella over :engine, :templates and :game, shipped as one XCFramework.
// `./gradlew :loupe-kit:assembleLoupeKitXCFramework` (macOS only; see docs/BUILD.md).
val appleHost = System.getProperty("os.name").startsWith("Mac")
// Laya on iOS (ORT + the Rust tokenizer) is exported when settings.gradle.kts included it, i.e. once
// ios-native/build.sh has run. Without it LoupeKit builds as before and the app cannot link Laya.
val layaIos = rootProject.findProject(":backend-onnx-ios")

// Kotlin/Native tests have no classpath resources; the watcher tests read the shipped sample from
// the repo by path (the iOS simulator shares the host file system), as :sources-common's do.
val sampleDir = rootProject.file("sources-desktop/src/main/resources/dev/loupe/sources/sample")
val examplePack = rootProject.file("examples/packs/bistro-cloud.json")
// The shared phishing formula's test vectors (docs/PHISHING-FORMULA.md), run on the JVM and the iOS simulator.
val phishingVectors = rootProject.file("docs/phishing-vectors.json")
// Formula v1.2 vectors (docs/PHISHING-FORMULA.md §5b–§6.1) and the Phishing.Database samples (copied from
// Loupe Station's tests/fixtures/phishingdb with their NOTICE), both read by tests only, never shipped.
val phishingVectorsV12 = rootProject.file("docs/phishing-vectors-v1.2.json")
// Formula v1.3 vectors (self_vouching, email profile), byte-identical to Station's tests/fixtures (0ff886d).
val phishingVectorsV13 = rootProject.file("docs/phishing-vectors-v1.3.json")
val phishingDbFixtures = project.file("src/commonTest/fixtures/phishingdb")
// The cross-platform parity corpus (tools/parity/README.md) and its evaluator, shared with
// :android-app's debug build so the same cases also run on an emulator or phone.
val parityCorpus = rootProject.file("tools/parity/corpus.json")
val parityEvaluator = rootProject.file("tools/parity/kotlin")
// The differential host-parity fuzz: hrefs and text lines with Chrome's and the linkifiers' hosts.
val hostParityFuzz = rootProject.file("tools/parity/fuzz/pinned.json")
// The anchor-parity fuzz: mail documents with the hosts of the links Chrome's DOMParser finds in them.
val anchorParityFuzz = rootProject.file("tools/parity/fuzz/anchor-pinned.json")
// Round 9's end-tag regression documents with Chrome's hosts.
val endTagRegression = rootProject.file("tools/parity/fuzz/end-pinned.json")
// Round 10's comment-in-raw-text documents with Chrome's hosts.
val commentRegression = rootProject.file("tools/parity/fuzz/comment-pinned.json")
// Round 11's 2,000 tag-soup documents with the hosts of the links Chrome renders.
val tagSoupFuzz = rootProject.file("tools/parity/fuzz/tagsoup-pinned.json")
// Legitimate .eml files with the score origin/main (699761a) gives each: a ceiling, never exceeded.
val legitEmlDir = rootProject.file("tools/parity/eml")
// shared_hosts.json: copied verbatim from Loupe Station (laya_studio/online/shared_hosts.json, commit
// 4cb9026). It is the one source of the list: generateSharedHosts turns it into commonMain Kotlin.
val sharedHostsJson = project.file("data/shared_hosts.json")
val generateSharedHosts by tasks.registering {
    val outDir = layout.buildDirectory.dir("generated/sharedHosts/kotlin")
    inputs.file(sharedHostsJson)
    outputs.dir(outDir)
    doLast {
        val text = sharedHostsJson.readText()
        val body = Regex("\"hosts\"\\s*:\\s*\\[([^\\]]*)\\]").find(text)?.groupValues?.get(1)
            ?: error("shared_hosts.json: no hosts array")
        val hosts = Regex("\"([^\"]+)\"").findAll(body).map { it.groupValues[1].trim().lowercase() }.filter { it.isNotEmpty() }.toList()
        require(hosts.size >= 50) { "shared_hosts.json: only ${hosts.size} hosts" }
        val version = Regex("\"version\"\\s*:\\s*(\\d+)").find(text)?.groupValues?.get(1) ?: "0"
        val updated = Regex("\"updated\"\\s*:\\s*\"([^\"]*)\"").find(text)?.groupValues?.get(1) ?: ""
        val f = outDir.get().file("dev/loupe/kit/site/SharedHostsData.kt").asFile
        f.parentFile.mkdirs()
        f.writeText(
            "// GENERATED by :loupe-kit:generateSharedHosts from loupe-kit/data/shared_hosts.json. Do not edit.\n" +
                "package dev.loupe.kit.site\n\n" +
                "internal object SharedHostsData {\n" +
                "    const val VERSION: Int = " + version + "\n" +
                "    const val UPDATED: String = \"" + updated + "\"\n" +
                "    val HOSTS: List<String> = listOf(\n" +
                hosts.joinToString("") { "        \"" + it + "\",\n" } +
                "    )\n}\n",
        )
    }
}
// The calibration prior and confidence gates the phone ships (docs/MODEL-SETTINGS.md, format
// loupe-calibration / loupe-gates v1, fitted on our own graph by ModelPriorFitTest). One source of truth:
// the two files in data/model-prior/, embedded into commonMain Kotlin here and bundled by the iOS app.
val modelPriorDir = project.file("data/model-prior")
val generateModelPrior by tasks.registering {
    val outDir = layout.buildDirectory.dir("generated/modelPrior/kotlin")
    inputs.dir(modelPriorDir)
    outputs.dir(outDir)
    doLast {
        fun literal(text: String): String = "\"" + text.replace("\\", "\\\\").replace("\"", "\\\"")
            .replace("$", "\\$").replace("\n", "\\n").replace("\r", "") + "\""
        val f = outDir.get().file("dev/loupe/kit/settings/ModelPriorData.kt").asFile
        f.parentFile.mkdirs()
        f.writeText(
            "// GENERATED by :loupe-kit:generateModelPrior from loupe-kit/data/model-prior/. Do not edit.\n" +
                "package dev.loupe.kit.settings\n\n" +
                "internal object ModelPriorData {\n" +
                "    const val CALIBRATION_JSON: String = " + literal(modelPriorDir.resolve("model_calibration.json").readText()) + "\n" +
                "    const val GATES_JSON: String = " + literal(modelPriorDir.resolve("model_gates.json").readText()) + "\n" +
                "}\n",
        )
    }
}
val generateTestPaths by tasks.registering {
    val outDir = layout.buildDirectory.dir("generated/testPaths/kotlin")
    inputs.property("sample", sampleDir.absolutePath)
    inputs.property("examplePack", examplePack.absolutePath)
    inputs.property("phishingVectors", phishingVectors.absolutePath)
    inputs.property("phishingVectorsV12", phishingVectorsV12.absolutePath)
    inputs.property("phishingVectorsV13", phishingVectorsV13.absolutePath)
    inputs.property("phishingDbFixtures", phishingDbFixtures.absolutePath)
    inputs.property("sharedHostsJson", sharedHostsJson.absolutePath)
    inputs.property("modelPriorDir", modelPriorDir.absolutePath)
    inputs.property("parityCorpus", parityCorpus.absolutePath)
    inputs.property("hostParityFuzz", hostParityFuzz.absolutePath)
    inputs.property("anchorParityFuzz", anchorParityFuzz.absolutePath)
    inputs.property("endTagRegression", endTagRegression.absolutePath)
    inputs.property("commentRegression", commentRegression.absolutePath)
    inputs.property("tagSoupFuzz", tagSoupFuzz.absolutePath)
    inputs.property("legitEmlDir", legitEmlDir.absolutePath)
    val scratch = layout.buildDirectory.dir("tmp/kit-tests").get().asFile.absolutePath
    inputs.property("scratch", scratch)
    outputs.dir(outDir)
    doLast {
        val f = outDir.get().file("dev/loupe/kit/watchers/TestPaths.kt").asFile
        f.parentFile.mkdirs()
        f.writeText(
            "// GENERATED by :loupe-kit:generateTestPaths. Do not edit.\n" +
                "package dev.loupe.kit.watchers\n\n" +
                "internal const val SAMPLE_DIR: String = \"" + sampleDir.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val EXAMPLE_PACK: String = \"" + examplePack.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val PHISHING_VECTORS: String = \"" + phishingVectors.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val PHISHING_VECTORS_V12: String = \"" + phishingVectorsV12.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val PHISHING_VECTORS_V13: String = \"" + phishingVectorsV13.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val PHISHINGDB_FIXTURES: String = \"" + phishingDbFixtures.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val SHARED_HOSTS_JSON: String = \"" + sharedHostsJson.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val MODEL_PRIOR_DIR: String = \"" + modelPriorDir.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val PARITY_CORPUS: String = \"" + parityCorpus.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val HOST_PARITY_FUZZ: String = \"" + hostParityFuzz.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val ANCHOR_PARITY_FUZZ: String = \"" + anchorParityFuzz.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val END_TAG_REGRESSION: String = \"" + endTagRegression.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val COMMENT_REGRESSION: String = \"" + commentRegression.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val TAG_SOUP_FUZZ: String = \"" + tagSoupFuzz.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val LEGIT_EML_DIR: String = \"" + legitEmlDir.absolutePath.replace("\\", "/") + "\"\n" +
                "internal const val TEST_TMP: String = \"" + scratch.replace("\\", "/") + "\"\n",
        )
    }
}

// The tests read these from disk by path (TestPaths.kt above), not from the classpath, so each is an
// input of every test task: an edit to one of them alone re-runs the tests on the JVM, Android and the
// iOS simulator instead of leaving them UP-TO-DATE.
tasks.withType<AbstractTestTask>().configureEach {
    inputs.file(parityCorpus).withPropertyName("parityCorpus").withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.file(hostParityFuzz).withPropertyName("hostParityFuzz").withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.file(anchorParityFuzz).withPropertyName("anchorParityFuzz").withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.file(endTagRegression).withPropertyName("endTagRegression").withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.file(commentRegression).withPropertyName("commentRegression").withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.file(tagSoupFuzz).withPropertyName("tagSoupFuzz").withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.dir(legitEmlDir).withPropertyName("legitEmlDir").withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.file(phishingVectors).withPropertyName("phishingVectors").withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.file(phishingVectorsV12).withPropertyName("phishingVectorsV12").withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.file(examplePack).withPropertyName("examplePack").withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.file(sharedHostsJson).withPropertyName("sharedHostsJson").withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.dir(phishingDbFixtures).withPropertyName("phishingDbFixtures").withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.dir(sampleDir).withPropertyName("sampleDir").withPathSensitivity(PathSensitivity.RELATIVE)
}

kotlin {
    // A JVM target keeps the module an ordinary participant in `./gradlew build` on Linux CI.
    jvm()
    // Loupe for Android: :android-app depends on this module as the iPhone app does on LoupeKit.
    if (androidHost) {
        androidTarget {
            compilerOptions {
                jvmTarget.set(JvmTarget.JVM_17)
            }
        }
    }

    if (appleHost) {
        val xcf = XCFramework("LoupeKit")
        listOf(iosArm64(), iosSimulatorArm64()).forEach { target ->
            target.binaries.framework {
                baseName = "LoupeKit"
                isStatic = true
                export(project(":engine"))
                export(project(":templates"))
                export(project(":game"))
                export(project(":persistence"))
                export(project(":sources-common"))
                if (layaIos != null) {
                    export(layaIos)
                    export(project(":backend-laya-common"))
                }
                xcf.add(this)
            }
        }
    }

    // jvmCommon: the JVM actuals, shared as is by the desktop JVM and Android (docs/ANDROID-PLAN.md,
    // "no logic forks").
    @OptIn(org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi::class)
    applyDefaultHierarchyTemplate {
        common {
            group("jvmCommon") {
                withJvm()
                withAndroidTarget()
            }
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateSharedHosts)
            kotlin.srcDir(generateModelPrior)
        }
        commonMain.dependencies {
            api(project(":engine"))
            api(project(":templates"))
            // The game (Riverflight) for the iPhone app: rules, pilots, GameSessions, HostedDecider.
            api(project(":game"))
            // The ledger on the phone (epic #7 child 1): PhoneLedger, the files, the F4 export.
            api(project(":persistence"))
            // Sources on the phone (epic #7 child 2): SourceItem, the common extractors and scanner, the cache.
            api(project(":sources-common"))
        }
        commonTest {
            kotlin.srcDir(generateTestPaths)
            kotlin.srcDir(parityEvaluator)
            dependencies {
                implementation(kotlin("test"))
            }
        }
        // The sample's PDFs need a real reader: PDFBox (through :sources-desktop) on the JVM,
        // PDFKit on the iOS simulator — the readers each app uses. Android's unit tests run on the
        // host JVM and share the JVM's (jvmCommonTest); the phone's own PDF reader comes with the
        // Android sources milestone (A4), and is never PDFBox.
        getByName("jvmCommonTest").dependencies {
            implementation(project(":sources-desktop"))
        }
        // Tests only: the gated real-model measurement (ModelFixesMeasurementTest) loads Laya through
        // the ONNX backend, as :game's gated tests do. Never on the kit's runtime classpath.
        jvmTest.dependencies {
            implementation(project(":backend-onnx"))
        }
        if (appleHost && layaIos != null) {
            iosMain {
                // Only compiled when Laya for iOS is present, since it calls into it.
                kotlin.srcDir("src/iosLaya/kotlin")
                dependencies {
                    api(layaIos)
                    api(project(":backend-laya-common"))
                }
            }
        }
    }
}

if (androidHost) {
    extensions.configure<com.android.build.api.dsl.LibraryExtension> {
        namespace = "dev.loupe.kit"
        compileSdk = 36
        defaultConfig {
            minSdk = 29
        }
        compileOptions {
            sourceCompatibility = JavaVersion.VERSION_17
            targetCompatibility = JavaVersion.VERSION_17
        }
    }
}


tasks.named<Test>("jvmTest") {
    // The gated measurement looks for the gitignored Laya weights here and skips without them.
    val models = rootProject.file("models")
    systemProperty("loupe.models.dir", models.absolutePath)
    // Declared as inputs so a result is never replayed from the build cache across the weights
    // appearing or disappearing (the trap recorded in docs/BUILD.md's hand-off).
    inputs.files(
        fileTree(models) {
            include("laya-multilingual/tokenizer/tokenizer.json", "laya-multilingual-onnx/laya-multilingual-choice.int8.onnx")
        },
    ).withPropertyName("layaModels").withPathSensitivity(PathSensitivity.RELATIVE).optional()
    // ModelPriorFitTest writes the fitted files into data/model-prior/ only when asked:
    //   ./gradlew :loupe-kit:jvmTest --tests '*ModelPriorFitTest' -Ploupe.fit.write=true
    providers.gradleProperty("loupe.fit.write").orNull?.let { systemProperty("loupe.fit.write", it) }
    maxHeapSize = "1g"
}
