import Foundation
import SwiftUI

/// The live run view's words: Loupe Station's `act.*` catalogue (static/js/i18n.js, English and Arabic, verbatim
/// except "this Mac", which reads "this device" here), then the phone's own keys. The same keys as Station, so a job
/// means the same thing on both. Arabic follows the phone's language (or `-LoupeLanguage ar`), as Model settings.
enum ActStrings {
    static var lang: MS.Lang { MS.lang }
    static var direction: LayoutDirection { MS.direction }

    /// The line for [key] with `{name}` placeholders filled; the key itself when the catalogue lacks it.
    static func t(_ key: String, _ args: [String: String] = [:]) -> String {
        let pair = table[key]
        var s = (lang == .ar ? pair?.1 : pair?.0) ?? pair?.0 ?? key
        for (k, v) in args { s = s.replacingOccurrences(of: "{\(k)}", with: v) }
        return s
    }

    static func has(_ key: String) -> Bool { table[key] != nil }

    static let table: [String: (String, String)] = [
        "act.kind.scan": ("Folder Scan", "فحص المجلدات"),
        "act.kind.email_run": ("Email run", "جولة البريد"),
        "act.kind.watchers": ("Watchers", "المراقِبات"),
        "act.kind.model_load": ("Laya model", "نموذج ⁦Laya⁩"),
        "act.kind.ocr": ("Reading images", "قراءة الصور"),
        "act.kind.ollama_pull": ("Model download", "تنزيل نموذج"),
        "act.kind.feeds": ("Phishing lists", "قوائم التصيّد"),
        "act.kind.llm_job": ("AI model job", "مهمة نموذج ذكاء اصطناعي"),
        "act.kind.calibration": ("Calibration", "المعايرة"),
        "act.title.scan": ("Folder Scan", "فحص المجلدات"),
        "act.title.email": ("Email run", "جولة البريد"),
        "act.kind.mail_history": ("Mail history sync", "مزامنة سجل البريد"),
        "act.title.mailHistory": ("Mail history sync", "مزامنة سجل البريد"),
        "act.stage.history.searching": ("Searching the mailbox", "البحث في صندوق البريد"),
        "act.stage.history.headers": ("Reading headers", "قراءة الترويسات"),
        "act.stage.history.candidates": ("Fetching candidates", "جلب الرسائل المرشحة"),
        "act.stage.history.extracting": ("Extracting facts", "استخراج الحقائق"),
        "act.stage.history.feeding": ("Feeding the watchers", "تغذية المراقِبات"),
        "act.stage.history.waiting": ("Waiting (the model is busy, or the mail provider asked to slow down)", "انتظار (النموذج مشغول، أو طلب مزوّد البريد الإبطاء)"),
        "act.step.history.search": ("Searches", "عمليات البحث"),
        "act.step.history.headers": ("Headers read", "الترويسات المقروءة"),
        "act.step.history.fetch": ("Candidates", "المرشحة"),
        "act.step.history.extract": ("Bodies and documents", "النصوص والمستندات"),
        "act.step.history.feed": ("Watchers", "المراقِبات"),
        "act.res.mailHistory": ("Read {seen} messages: {receipts} receipts and billing emails, {documents} documents", "قُرئت رسائل عددها {seen}: الإيصالات ورسائل الفواتير {receipts}، والمستندات {documents}"),
        "act.res.mailHistoryStopped": ("Stopped after {seen} messages; the next sync continues from here", "توقفت بعد قراءة رسائل عددها {seen}؛ تكمل المزامنة التالية من هنا"),
        "act.title.watchers": ("Watcher run", "جولة المراقِبات"),
        "act.title.modelLoad": ("Loading the {model} model", "تحميل النموذج {model}"),
        "act.title.modelUnload": ("Unloaded the {model} model", "أُفرغ النموذج {model}"),
        "act.title.memoryMode": ("Memory mode: {mode}", "وضع الذاكرة: {mode}"),
        "act.title.ollamaPull": ("Downloading {model}", "تنزيل {model}"),
        "act.title.feeds": ("Refreshing the phishing lists", "تحديث قوائم التصيّد"),
        "act.title.drafts": ("Reply drafts", "مسودات الردود"),
        "act.title.secondOpinion": ("Second opinions", "آراء ثانية"),
        "act.title.calibration": ("Calibration fit", "ملاءمة المعايرة"),
        "act.stage.walking": ("Listing the files", "سرد الملفات"),
        "act.stage.deciding": ("Reading and deciding", "القراءة واتخاذ القرار"),
        "act.stage.waiting_models": ("Waiting for the Laya models", "بانتظار نماذج ⁦Laya⁩"),
        "act.stage.hashing": ("Looking for duplicates", "البحث عن النسخ المكررة"),
        "act.stage.finishing": ("Finishing", "الإنهاء"),
        "act.stage.fetching": ("Fetching", "الجلب"),
        "act.stage.classifying": ("Classifying", "التصنيف"),
        "act.stage.refining": ("Refining important emails", "تدقيق الرسائل المهمة"),
        "act.stage.starting": ("Starting", "البدء"),
        "act.stage.watcher": ("Running {watcher}", "تشغيل {watcher}"),
        "act.stage.loadingModel": ("Loading into memory", "التحميل إلى الذاكرة"),
        "act.stage.connecting": ("Connecting to Ollama", "الاتصال بـ ⁦Ollama⁩"),
        "act.stage.downloading": ("Downloading", "التنزيل"),
        "act.stage.verifying": ("Checking the download", "التحقق من التنزيل"),
        "act.stage.asking": ("Asking the AI model", "سؤال نموذج الذكاء الاصطناعي"),
        "act.stage.fitting": ("Fitting per question", "الملاءمة لكل سؤال"),
        "act.res.scan": ("Files checked: {files} · flagged: {flagged}", "الملفات المفحوصة: {files} · المُعلَّمة: {flagged}"),
        "act.res.stopped": ("Stopped early", "توقّف مبكرًا"),
        "act.res.email": ("Emails: {emails} · flagged: {flagged} · uncertain: {uncertain}", "الرسائل: {emails} · المُعلَّمة: {flagged} · غير المؤكدة: {uncertain}"),
        "act.res.emailCancelled": ("Stopped early; kept {emails} emails", "توقّف مبكرًا؛ احتُفظ بـ {emails} رسالة"),
        "act.res.failed": ("Stopped with an error", "توقّف بخطأ"),
        "act.res.watchers": ("New findings: {new} · open: {found}", "نتائج جديدة: {new} · مفتوحة: {found}"),
        "act.res.watcher": ("New findings: {new} · open: {found}", "نتائج جديدة: {new} · مفتوحة: {found}"),
        "act.res.watcherNot": ("Not run ({status})", "لم يعمل ({status})"),
        "act.res.modelLoaded": ("Ready in {seconds} s", "جاهز خلال {seconds} ث"),
        "act.res.modelFailed": ("Could not load the {model} model", "تعذّر تحميل النموذج {model}"),
        "act.res.modelUnloaded": ("Memory freed", "تحرّرت الذاكرة"),
        "act.res.memoryMode": ("Applied", "طُبّق"),
        "act.res.pulled": ("Downloaded {bytes}", "نُزّل {bytes}"),
        "act.res.list": ("Entries: {entries}", "الإدخالات: {entries}"),
        "act.res.feeds": ("Lists refreshed: {lists}", "القوائم المحدّثة: {lists}"),
        "act.res.llm": ("Done: {done} · failed: {errors}", "تم: {done} · فشل: {errors}"),
        "act.res.fit": ("Labels: {n}", "التصنيفات: {n}"),
        "act.res.calibration": ("Questions: {questions} · fitted: {fitted}", "الأسئلة: {questions} · المُلاءمة: {fitted}"),
        "act.step.fetch": ("Fetching", "الجلب"),
        "act.step.classify": ("Classifying", "التصنيف"),
        "act.step.refine": ("Refining important emails", "تدقيق الرسائل المهمة"),
        "act.step.waiting": ("Waiting", "بالانتظار"),
        "act.step.skipped": ("Not needed", "غير لازم"),
        "act.stepState.pending": ("waiting", "بالانتظار"),
        "act.stepState.running": ("running now", "يعمل الآن"),
        "act.stepState.done": ("done", "تم"),
        "act.stepState.error": ("failed", "فشل"),
        "act.stepState.skipped": ("skipped", "تُخطّي"),
        "act.state.running": ("Running", "يعمل"),
        "act.state.done": ("Done", "تم"),
        "act.state.error": ("Failed", "فشل"),
        "act.state.cancelled": ("Cancelled", "أُلغي"),
        "act.model.english": ("English", "الإنجليزي"),
        "act.model.multilingual": ("multilingual", "متعدد اللغات"),
        "act.model.auto": ("auto routing", "توجيه تلقائي"),
        "act.mode.full": ("Full", "كامل"),
        "act.mode.balanced": ("Balanced", "متوازن"),
        "act.mode.low": ("Low", "منخفض"),
        "act.dur.s": ("{n} s", "⁦{n}⁩ ث"),
        "act.dur.min": ("{n} min", "⁦{n}⁩ دقيقة"),
        "act.dur.h": ("{h} h {n} min", "⁦{h}⁩ س ⁦{n}⁩ دقيقة"),
        "act.eta": ("about {d} left", "بقي نحو {d}"),
        "act.etaSoon": ("almost done", "أوشك على الانتهاء"),
        "act.ratePer": ("{n} / s", "{n} / ث"),
        "act.of": ("{done} of {total}", "{done} من {total}"),
        "act.checked": ("{n} checked", "فُحص {n}"),
        "act.reads": ("reads {n} of {max}", "قراءات {n} من {max}"),
        "act.elapsed": ("{d} elapsed", "مضى {d}"),
        "act.ago": ("{d} ago", "منذ {d}"),
        "act.progress": ("Progress", "التقدّم"),
        "act.cancel": ("Cancel", "إلغاء"),
        "act.cancelling": ("Cancelling…", "جارٍ الإلغاء…"),
        "act.show": ("Show", "عرض"),
        "act.close": ("Close", "إغلاق"),
        "act.panel.title": ("Activity", "النشاط"),
        "act.panel.running": ("Running now", "يعمل الآن"),
        "act.panel.finished": ("Finished", "انتهى"),
        "act.panel.empty": ("Nothing has run since Loupe started.", "لم يعمل شيء منذ بدء ⁦Loupe⁩."),
        "act.chip.idle": ("Activity", "النشاط"),
        "act.chip.many": ("{n} running · {lead}", "{n} قيد التشغيل · {lead}"),
        "act.chip.aria": ("Activity: {n} running. {lead}", "النشاط: {n} قيد التشغيل. {lead}"),
        "act.live.started": ("{title} started", "بدأ {title}"),
        "act.banner.loading": ("Loading the {model} model…", "جارٍ تحميل النموذج {model}…"),
        "act.banner.loadingEta": ("Loading the {model} model… about {d}", "جارٍ تحميل النموذج {model}… نحو {d}"),
        "act.banner.aria": ("Model loading", "تحميل النموذج"),
        "act.liveView": ("Live run", "التشغيل المباشر"),
        "act.ctr.read": ("Read", "قُرئ"),
        "act.ctr.decisions": ("Decisions", "القرارات"),
        "act.ctr.flagged": ("Flagged", "المُعلَّمة"),
        "act.ctr.to_you": ("Sent to you", "أُرسل إليك"),
        "act.card.log": ("Decision log", "سجل القرارات"),
        "act.card.shares": ("Who answered", "من أجاب"),
        "act.card.cost": ("Cost of asking", "كلفة السؤال"),
        "act.card.gates": ("Where items went", "أين ذهبت العناصر"),
        "act.log.empty": ("No decisions yet.", "لا قرارات بعد."),
        "act.share.english": ("Laya · English", "⁦Laya⁩ · الإنجليزي"),
        "act.share.multilingual": ("Laya · multilingual", "⁦Laya⁩ · متعدد اللغات"),
        "act.share.rule": ("Rules", "القواعد"),
        "act.share.baseline": ("Keyword baseline", "خط أساس الكلمات"),
        "act.share.personal": ("Your corrections", "تصحيحاتك"),
        "act.src.laya": ("laya", "لايا"),
        "act.src.rule": ("rule", "قاعدة"),
        "act.src.baseline": ("baseline", "خط أساس"),
        "act.src.personal": ("you", "أنت"),
        "act.cost.cloud": ("Ask {model}", "سؤال {model}"),
        "act.cost.local": ("Ask Laya on this device", "سؤال ⁦Laya⁩ على هذا الجهاز"),
        "act.cost.free": ("free", "مجانًا"),
        "act.cost.saved": ("Saved by deciding on this device", "وُفّر بالقرار على هذا الجهاز"),
        "act.cost.decisions": ("{n} decisions, each an estimated cloud request", "{n} قرارًا، كلٌّ منها طلب سحابي تقديري"),
        "act.cost.estimate": ("estimate · {model} list price as of {date}", "تقدير · سعر {model} المعلن في {date}"),
        "act.cost.custom": ("estimate · your price from Model settings", "تقدير · سعرك من إعدادات النموذج"),
        "act.gate.accepted": ("Accepted", "مقبولة"),
        "act.gate.uncertain": ("Uncertain, spot check", "غير مؤكدة، للمراجعة"),
        "act.gate.flagged": ("Flagged", "مُعلَّمة"),
        "act.gate.skipped": ("Skipped", "مُتخطّاة"),
        "act.poweredBy": ("powered by Laya · {model}", "بقوة ⁦Laya⁩ · {model}"),
        "act.coreCaption": ("Deciding {pct}%", "يقرّر {pct}%"),
        "act.unit.emails": ("emails", "رسائل"),
        "act.unit.files": ("files", "ملفات"),
        "act.unit.items": ("items read", "عناصر مقروءة"),
        "act.node.fetch": ("Fetch", "الجلب"),
        "act.node.fetchSub": ("from the mailbox", "من صندوق البريد"),
        "act.node.read": ("Read", "القراءة"),
        "act.node.readSub": ("preview, then full", "معاينة ثم كامل"),
        "act.node.rules": ("Rules gate", "بوابة القواعد"),
        "act.node.rulesSub": ("sure rules first", "القواعد الأكيدة أولًا"),
        "act.node.evidence": ("Phishing check", "فحص التصيّد"),
        "act.node.evidenceSub": ("sender and links", "المرسل والروابط"),
        "act.node.outcome": ("Labelled", "مُصنَّفة"),
        "act.node.outcomeSub": ("ready to apply", "جاهزة للتطبيق"),
        "act.node.review": ("Sent to you", "أُرسلت إليك"),
        "act.node.reviewSub": ("spot check, flagged", "مراجعة، مُعلَّمة"),
        "act.node.walk": ("List files", "سرد الملفات"),
        "act.node.walkSub": ("the folder you chose", "المجلد الذي اخترته"),
        "act.node.readFile": ("Read", "القراءة"),
        "act.node.readFileSub": ("text and images", "النصوص والصور"),
        "act.node.detectors": ("Detectors", "الكواشف"),
        "act.node.detectorsSub": ("secrets, personal data", "أسرار وبيانات شخصية"),
        "act.node.dupes": ("Duplicates", "النسخ المكررة"),
        "act.node.dupesSub": ("same content", "المحتوى نفسه"),
        "act.node.outcomeFileSub": ("labelled files", "ملفات مصنّفة"),
        "act.node.reviewFile": ("Needs a look", "تحتاج نظرة"),
        "act.node.reviewFileSub": ("risky or uncertain", "خطرة أو غير مؤكدة"),
        "act.node.items": ("Your items", "عناصرك"),
        "act.node.itemsSub": ("emails, files, statements", "رسائل وملفات وكشوف"),
        "act.node.readItem": ("Read", "القراءة"),
        "act.node.readItemSub": ("40 reads a watcher", "٤٠ قراءة لكل مراقِب"),
        "act.node.findings": ("Findings", "النتائج"),
        "act.node.findingsSub": ("with evidence", "مع الأدلة"),
        "act.node.outcomeItemSub": ("checked", "فُحصت"),
        "act.node.reminders": ("Reminders", "التذكيرات"),
        "act.node.remindersSub": ("in Review", "في المراجعة"),
        "act.node.search": ("Search", "البحث"),
        "act.node.searchSub": ("receipts, documents", "إيصالات ومستندات"),
        "act.node.headersSub": ("headers first", "الترويسات أولًا"),
        "act.node.extract": ("Extract", "الاستخراج"),
        "act.node.extractSub": ("dates and amounts", "تواريخ ومبالغ"),
        "act.node.stored": ("Stored", "الحفظ"),
        "act.node.storedSub": ("on this device only", "على هذا الجهاز فقط"),
        "act.node.feedWatchers": ("Watchers", "المراقِبات"),
        "act.node.feedWatchersSub": ("fed with the history", "تتغذى بالسجل"),
        "act.q.category": ("which team?", "أي فريق؟"),
        "act.q.needs_reply": ("needs a reply?", "يحتاج ردًا؟"),
        "act.q.urgency": ("how urgent?", "ما مدى الإلحاح؟"),
        "act.q.is_spam": ("spam?", "مزعجة؟"),
        "act.q.is_phishing": ("phishing?", "تصيّد؟"),
        "act.q.business": ("business or personal?", "عمل أم شخصي؟"),
        "act.q.sensitive": ("sensitive?", "حساس؟"),
        "act.q.draft": ("a draft?", "مسودة؟"),
        "act.watch.results": ("Last run", "آخر جولة"),
        "act.watch.newFindings": ("{n} new findings", "{n} نتيجة جديدة"),
        "act.watch.notRun": ("not run", "لم يعمل"),
        // The phone's own keys (docs/LIVE-RUN-VIEW.md).
        "act.kind.judgments": ("Judgment run", "تشغيل حكم"),
        "act.kind.sort": ("Background sort", "الفرز في الخلفية"),
        "act.kind.inbox": ("Inbox import", "استيراد إلى الوارد"),
        "act.kind.flights": ("Flight ranking", "ترتيب الرحلات"),
        "act.kind.game": ("Riverflight", "ريفرفلايت"),
        "act.kind.web_search": ("Web question", "سؤال الويب"),
        "act.title.privacy": ("Privacy check", "فحص الخصوصية"),
        "act.title.mail": ("Mail triage", "فرز البريد"),
        "act.title.judgments": ("Judgment run", "تشغيل حكم"),
        "act.title.sort": ("Sorting in the background", "الفرز في الخلفية"),
        "act.title.inbox": ("Importing to the Inbox", "الاستيراد إلى الوارد"),
        "act.title.flights": ("Ranking flights", "ترتيب الرحلات"),
        "act.title.webSearch": ("Answering your Web question", "الإجابة عن سؤالك على الويب"),
        "act.title.game": ("Riverflight: the pilot decides", "ريفرفلايت: الطيّار يقرّر"),
        "act.title.modelDownload": ("Downloading the {model} model", "تنزيل النموذج {model}"),
        "act.title.writing": ("Writing assistant", "مساعد الكتابة"),
        "act.stage.ranking": ("Ranking by your priorities", "الترتيب حسب أولوياتك"),
        "act.stage.playing": ("The pilot is deciding", "الطيّار يقرّر"),
        "act.stage.importing": ("Importing what you shared", "استيراد ما شاركته"),
        "act.res.judgments": ("Judged: {done} · uncertain: {uncertain}", "حُكم على: {done} · غير المؤكدة: {uncertain}"),
        "act.res.sort": ("Sorted: {done}", "فُرز: {done}"),
        "act.res.inbox": ("Imported: {items}", "استُورد: {items}"),
        "act.res.flights": ("Ranked: {offers}", "رُتّب: {offers}"),
        "act.res.webSearch": ("Judged: {items}", "حُكم على: {items}"),
        "act.res.game": ("Score {score} · {rows} rows", "النتيجة {score} · {rows} صفًا"),
        "act.res.downloaded": ("Downloaded and checked", "نُزّل وتُحقّق منه"),
        "act.res.writing": ("Draft ready for Review", "المسودة جاهزة للمراجعة"),
        "act.cost.onDevice": ("on this device, free", "على هذا الجهاز، مجانًا"),
        "act.q.flight": ("best offer?", "أفضل عرض؟"),
        "act.q.web.search.yes_no": ("yes or no?", "نعم أم لا؟"),
        "act.q.web.search.pick": ("the best one?", "الأفضل؟"),
        "act.q.web.search.score": ("how well?", "إلى أي حد؟"),
        "act.q.web.search.rank": ("how well?", "إلى أي حد؟"),
        "act.q.move": ("which way?", "أي اتجاه؟"),
        "act.status.running": ("{title}: {stage}", "{title}: {stage}"),
        "act.dock.show": ("Show activity", "عرض النشاط"),
    ]
}
