package dev.loupe.engine

import java.net.IDN
import java.text.Normalizer
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * JVM-only: pins Loupe's own Unicode data and normalizer (PortableText, generated by
 * tools/unicode/gen_unicode_tables.py from the Unicode 16.0 UCD) against the JDK's, on every code
 * point the JDK knows. JDK 21 implements Unicode 15.0; by the normalization stability policy every
 * mapping of a 15.0 character is unchanged in 16.0, so the two must agree on all of them.
 */
class UnicodeDataJvmTest {

    private fun str(cp: Int) = String(Character.toChars(cp))

    private val jdkDefined: List<Int> =
        (0..Character.MAX_CODE_POINT).filter { Character.isDefined(it) && Character.getType(it) != Character.SURROGATE.toInt() }

    @Test
    fun `NFC NFD NFKC and NFKD match java-text-Normalizer on every code point the JDK defines`() {
        var checked = 0
        for (cp in jdkDefined) {
            val s = str(cp)
            assertEquals(Normalizer.normalize(s, Normalizer.Form.NFC), PortableText.nfc(s), "NFC U+%04X".format(cp))
            assertEquals(Normalizer.normalize(s, Normalizer.Form.NFD), PortableText.nfd(s), "NFD U+%04X".format(cp))
            assertEquals(Normalizer.normalize(s, Normalizer.Form.NFKC), PortableText.nfkc(s), "NFKC U+%04X".format(cp))
            assertEquals(Normalizer.normalize(s, Normalizer.Form.NFKD), PortableText.nfkd(s), "NFKD U+%04X".format(cp))
            checked++
        }
        assertTrue(checked > 280_000, "only $checked code points")
    }

    @Test
    fun `normal forms of mixed strings match the JDK`() {
        val samples = listOf(
            "Ångström ﬁ ①", "ẹ́ ạ́", "각 한국어", "ｆｕｌｌ　ｗｉｄｔｈ", "ﾃｽﾄ",
            "الْعَرَبِيّة", "ﷺ", "ẍ̧́",
            "ཱཱཱིྀུ̈́", "𝅗𝅥𝅥", "ÅΩK", "क़ख़ ড়",
        )
        for (s in samples) {
            for (form in Normalizer.Form.entries) {
                val got = when (form) {
                    Normalizer.Form.NFC -> PortableText.nfc(s)
                    Normalizer.Form.NFD -> PortableText.nfd(s)
                    Normalizer.Form.NFKC -> PortableText.nfkc(s)
                    Normalizer.Form.NFKD -> PortableText.nfkd(s)
                }
                assertEquals(Normalizer.normalize(s, form), got, "$form($s)")
            }
        }
    }

    @Test
    fun `simple fold is the JDK's lower of upper on every code point the JDK defines`() {
        // Case mappings of existing characters do not change between Unicode versions except where a
        // new case partner is added; those code points are listed here as they are found.
        val changedSince15 = emptySet<Int>()
        for (cp in jdkDefined) {
            if (cp in changedSince15) continue
            val want = Character.toLowerCase(Character.toUpperCase(cp))
            assertEquals(want, UnicodeData.fold(cp), "fold U+%04X".format(cp))
            assertEquals(Character.toLowerCase(cp), UnicodeData.lower(cp), "lower U+%04X".format(cp))
        }
    }

    @Test
    fun `lowercase matches String-lowercase except for the final sigma`() {
        for (s in listOf("İSTANBUL", "ΟΔΟΣ ΑΘΗΝΩΝ", "Straße", "ǅemal", "ĲSSEL", "Ωmega", "𐐀𐐁")) {
            assertEquals(s.lowercase().replace('ς', 'σ'), PortableText.lowercase(s).replace('ς', 'σ'), s)
        }
        assertEquals("οδοσ", PortableText.lowercase("ΟΔΟΣ"))
    }

    @Test
    fun `categories match the JDK on every code point the JDK defines`() {
        for (cp in jdkDefined) {
            val t = Character.getType(cp)
            val letter = Character.isLetter(cp)
            val number = t == Character.DECIMAL_DIGIT_NUMBER.toInt() || t == Character.LETTER_NUMBER.toInt() ||
                t == Character.OTHER_NUMBER.toInt()
            val mark = t == Character.NON_SPACING_MARK.toInt() || t == Character.ENCLOSING_MARK.toInt() ||
                t == Character.COMBINING_SPACING_MARK.toInt()
            assertEquals(letter, PortableText.isLetter(cp), "letter U+%04X".format(cp))
            assertEquals(number, PortableText.isNumber(cp), "number U+%04X".format(cp))
            assertEquals(mark, PortableText.isMark(cp), "mark U+%04X".format(cp))
        }
    }

    /**
     * STABLE32 comes from the Unicode 3.2 UCD and RFC 3454's tables; java.net.IDN implements the
     * same nameprep with its own copy. Wherever the JDK accepts a one-character label, a code point
     * the table calls stable must get the JDK's ASCII form from the pinned IDNA, and every code point
     * the JDK maps differently from the pinned IDNA must be outside the stable set.
     */
    @Test
    fun `the Unicode 3-2 drift set agrees with java-net-IDN`() {
        var compared = 0
        for (cp in 0x80..Character.MAX_CODE_POINT) {
            // Surrogates, and the dots IDN.toASCII treats as label separators (not a one-character label).
            if (cp in 0xD800..0xDFFF || cp == 0x3002 || cp == 0xFF0E || cp == 0xFF61) continue
            val jdk = runCatching { IDN.toASCII(str(cp), IDN.ALLOW_UNASSIGNED).lowercase() }.getOrNull() ?: continue
            if (jdk.isEmpty()) continue
            val pinned = Idna.toAsciiLabel(str(cp))
            if (PortableText.stableSinceUnicode32(cp)) {
                assertEquals(jdk, pinned, "stable U+%04X".format(cp))
                compared++
            } else if (Character.isDefined(cp) && Character.getType(cp) != Character.PRIVATE_USE.toInt()) {
                // Not stable: unassigned in 3.2 (the JDK passes it through), or mapped differently.
                val assigned32 = jdk != "xn--" + (Punycode.encode(str(cp)) ?: "")
                if (assigned32) assertTrue(jdk != pinned, "U+%04X is marked as drift but maps the same".format(cp))
            }
        }
        assertTrue(compared > 90_000, "only $compared stable code points compared")
    }
}
